// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetDestinationQdrant
    {
        public static Task<GetDestinationQdrantResult> InvokeAsync(GetDestinationQdrantArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDestinationQdrantResult>("airbyte:index/getDestinationQdrant:getDestinationQdrant", args ?? new GetDestinationQdrantArgs(), options.WithDefaults());

        public static Output<GetDestinationQdrantResult> Invoke(GetDestinationQdrantInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDestinationQdrantResult>("airbyte:index/getDestinationQdrant:getDestinationQdrant", args ?? new GetDestinationQdrantInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDestinationQdrantArgs : global::Pulumi.InvokeArgs
    {
        [Input("destinationId", required: true)]
        public string DestinationId { get; set; } = null!;

        public GetDestinationQdrantArgs()
        {
        }
        public static new GetDestinationQdrantArgs Empty => new GetDestinationQdrantArgs();
    }

    public sealed class GetDestinationQdrantInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("destinationId", required: true)]
        public Input<string> DestinationId { get; set; } = null!;

        public GetDestinationQdrantInvokeArgs()
        {
        }
        public static new GetDestinationQdrantInvokeArgs Empty => new GetDestinationQdrantInvokeArgs();
    }


    [OutputType]
    public sealed class GetDestinationQdrantResult
    {
        public readonly string Configuration;
        public readonly string DestinationId;
        public readonly string DestinationType;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetDestinationQdrantResult(
            string configuration,

            string destinationId,

            string destinationType,

            string id,

            string name,

            string workspaceId)
        {
            Configuration = configuration;
            DestinationId = destinationId;
            DestinationType = destinationType;
            Id = id;
            Name = name;
            WorkspaceId = workspaceId;
        }
    }
}
