// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetDestinationSnowflakeCortex
    {
        public static Task<GetDestinationSnowflakeCortexResult> InvokeAsync(GetDestinationSnowflakeCortexArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDestinationSnowflakeCortexResult>("airbyte:index/getDestinationSnowflakeCortex:getDestinationSnowflakeCortex", args ?? new GetDestinationSnowflakeCortexArgs(), options.WithDefaults());

        public static Output<GetDestinationSnowflakeCortexResult> Invoke(GetDestinationSnowflakeCortexInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDestinationSnowflakeCortexResult>("airbyte:index/getDestinationSnowflakeCortex:getDestinationSnowflakeCortex", args ?? new GetDestinationSnowflakeCortexInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDestinationSnowflakeCortexArgs : global::Pulumi.InvokeArgs
    {
        [Input("destinationId", required: true)]
        public string DestinationId { get; set; } = null!;

        public GetDestinationSnowflakeCortexArgs()
        {
        }
        public static new GetDestinationSnowflakeCortexArgs Empty => new GetDestinationSnowflakeCortexArgs();
    }

    public sealed class GetDestinationSnowflakeCortexInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("destinationId", required: true)]
        public Input<string> DestinationId { get; set; } = null!;

        public GetDestinationSnowflakeCortexInvokeArgs()
        {
        }
        public static new GetDestinationSnowflakeCortexInvokeArgs Empty => new GetDestinationSnowflakeCortexInvokeArgs();
    }


    [OutputType]
    public sealed class GetDestinationSnowflakeCortexResult
    {
        public readonly string Configuration;
        public readonly string DestinationId;
        public readonly string DestinationType;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetDestinationSnowflakeCortexResult(
            string configuration,

            string destinationId,

            string destinationType,

            string id,

            string name,

            string workspaceId)
        {
            Configuration = configuration;
            DestinationId = destinationId;
            DestinationType = destinationType;
            Id = id;
            Name = name;
            WorkspaceId = workspaceId;
        }
    }
}
