// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceGoogleDrive
    {
        public static Task<GetSourceGoogleDriveResult> InvokeAsync(GetSourceGoogleDriveArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceGoogleDriveResult>("airbyte:index/getSourceGoogleDrive:getSourceGoogleDrive", args ?? new GetSourceGoogleDriveArgs(), options.WithDefaults());

        public static Output<GetSourceGoogleDriveResult> Invoke(GetSourceGoogleDriveInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceGoogleDriveResult>("airbyte:index/getSourceGoogleDrive:getSourceGoogleDrive", args ?? new GetSourceGoogleDriveInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceGoogleDriveArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceGoogleDriveArgs()
        {
        }
        public static new GetSourceGoogleDriveArgs Empty => new GetSourceGoogleDriveArgs();
    }

    public sealed class GetSourceGoogleDriveInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceGoogleDriveInvokeArgs()
        {
        }
        public static new GetSourceGoogleDriveInvokeArgs Empty => new GetSourceGoogleDriveInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceGoogleDriveResult
    {
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceGoogleDriveResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
