// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceSmartsheets
    {
        public static Task<GetSourceSmartsheetsResult> InvokeAsync(GetSourceSmartsheetsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceSmartsheetsResult>("airbyte:index/getSourceSmartsheets:getSourceSmartsheets", args ?? new GetSourceSmartsheetsArgs(), options.WithDefaults());

        public static Output<GetSourceSmartsheetsResult> Invoke(GetSourceSmartsheetsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceSmartsheetsResult>("airbyte:index/getSourceSmartsheets:getSourceSmartsheets", args ?? new GetSourceSmartsheetsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceSmartsheetsArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceSmartsheetsArgs()
        {
        }
        public static new GetSourceSmartsheetsArgs Empty => new GetSourceSmartsheetsArgs();
    }

    public sealed class GetSourceSmartsheetsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceSmartsheetsInvokeArgs()
        {
        }
        public static new GetSourceSmartsheetsInvokeArgs Empty => new GetSourceSmartsheetsInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceSmartsheetsResult
    {
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceSmartsheetsResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
