// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceAmazonSellerPartner
    {
        public static Task<GetSourceAmazonSellerPartnerResult> InvokeAsync(GetSourceAmazonSellerPartnerArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceAmazonSellerPartnerResult>("airbyte:index/getSourceAmazonSellerPartner:getSourceAmazonSellerPartner", args ?? new GetSourceAmazonSellerPartnerArgs(), options.WithDefaults());

        public static Output<GetSourceAmazonSellerPartnerResult> Invoke(GetSourceAmazonSellerPartnerInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceAmazonSellerPartnerResult>("airbyte:index/getSourceAmazonSellerPartner:getSourceAmazonSellerPartner", args ?? new GetSourceAmazonSellerPartnerInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceAmazonSellerPartnerArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceAmazonSellerPartnerArgs()
        {
        }
        public static new GetSourceAmazonSellerPartnerArgs Empty => new GetSourceAmazonSellerPartnerArgs();
    }

    public sealed class GetSourceAmazonSellerPartnerInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceAmazonSellerPartnerInvokeArgs()
        {
        }
        public static new GetSourceAmazonSellerPartnerInvokeArgs Empty => new GetSourceAmazonSellerPartnerInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceAmazonSellerPartnerResult
    {
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceAmazonSellerPartnerResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
