// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceMixpanel
    {
        public static Task<GetSourceMixpanelResult> InvokeAsync(GetSourceMixpanelArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceMixpanelResult>("airbyte:index/getSourceMixpanel:getSourceMixpanel", args ?? new GetSourceMixpanelArgs(), options.WithDefaults());

        public static Output<GetSourceMixpanelResult> Invoke(GetSourceMixpanelInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceMixpanelResult>("airbyte:index/getSourceMixpanel:getSourceMixpanel", args ?? new GetSourceMixpanelInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceMixpanelArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceMixpanelArgs()
        {
        }
        public static new GetSourceMixpanelArgs Empty => new GetSourceMixpanelArgs();
    }

    public sealed class GetSourceMixpanelInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceMixpanelInvokeArgs()
        {
        }
        public static new GetSourceMixpanelInvokeArgs Empty => new GetSourceMixpanelInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceMixpanelResult
    {
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceMixpanelResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
