// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceTrello
    {
        public static Task<GetSourceTrelloResult> InvokeAsync(GetSourceTrelloArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceTrelloResult>("airbyte:index/getSourceTrello:getSourceTrello", args ?? new GetSourceTrelloArgs(), options.WithDefaults());

        public static Output<GetSourceTrelloResult> Invoke(GetSourceTrelloInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceTrelloResult>("airbyte:index/getSourceTrello:getSourceTrello", args ?? new GetSourceTrelloInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceTrelloArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceTrelloArgs()
        {
        }
        public static new GetSourceTrelloArgs Empty => new GetSourceTrelloArgs();
    }

    public sealed class GetSourceTrelloInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceTrelloInvokeArgs()
        {
        }
        public static new GetSourceTrelloInvokeArgs Empty => new GetSourceTrelloInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceTrelloResult
    {
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceTrelloResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
