// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourcePostmarkapp
    {
        public static Task<GetSourcePostmarkappResult> InvokeAsync(GetSourcePostmarkappArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourcePostmarkappResult>("airbyte:index/getSourcePostmarkapp:getSourcePostmarkapp", args ?? new GetSourcePostmarkappArgs(), options.WithDefaults());

        public static Output<GetSourcePostmarkappResult> Invoke(GetSourcePostmarkappInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourcePostmarkappResult>("airbyte:index/getSourcePostmarkapp:getSourcePostmarkapp", args ?? new GetSourcePostmarkappInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourcePostmarkappArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourcePostmarkappArgs()
        {
        }
        public static new GetSourcePostmarkappArgs Empty => new GetSourcePostmarkappArgs();
    }

    public sealed class GetSourcePostmarkappInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourcePostmarkappInvokeArgs()
        {
        }
        public static new GetSourcePostmarkappInvokeArgs Empty => new GetSourcePostmarkappInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourcePostmarkappResult
    {
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourcePostmarkappResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
