// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceNytimes
    {
        public static Task<GetSourceNytimesResult> InvokeAsync(GetSourceNytimesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceNytimesResult>("airbyte:index/getSourceNytimes:getSourceNytimes", args ?? new GetSourceNytimesArgs(), options.WithDefaults());

        public static Output<GetSourceNytimesResult> Invoke(GetSourceNytimesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceNytimesResult>("airbyte:index/getSourceNytimes:getSourceNytimes", args ?? new GetSourceNytimesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceNytimesArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceNytimesArgs()
        {
        }
        public static new GetSourceNytimesArgs Empty => new GetSourceNytimesArgs();
    }

    public sealed class GetSourceNytimesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceNytimesInvokeArgs()
        {
        }
        public static new GetSourceNytimesInvokeArgs Empty => new GetSourceNytimesInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceNytimesResult
    {
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceNytimesResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
