// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceInsightly
    {
        public static Task<GetSourceInsightlyResult> InvokeAsync(GetSourceInsightlyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceInsightlyResult>("airbyte:index/getSourceInsightly:getSourceInsightly", args ?? new GetSourceInsightlyArgs(), options.WithDefaults());

        public static Output<GetSourceInsightlyResult> Invoke(GetSourceInsightlyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceInsightlyResult>("airbyte:index/getSourceInsightly:getSourceInsightly", args ?? new GetSourceInsightlyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceInsightlyArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceInsightlyArgs()
        {
        }
        public static new GetSourceInsightlyArgs Empty => new GetSourceInsightlyArgs();
    }

    public sealed class GetSourceInsightlyInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceInsightlyInvokeArgs()
        {
        }
        public static new GetSourceInsightlyInvokeArgs Empty => new GetSourceInsightlyInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceInsightlyResult
    {
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceInsightlyResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
