// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte
{
    public static class GetSourceFacebookMarketing
    {
        public static Task<GetSourceFacebookMarketingResult> InvokeAsync(GetSourceFacebookMarketingArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSourceFacebookMarketingResult>("airbyte:index/getSourceFacebookMarketing:getSourceFacebookMarketing", args ?? new GetSourceFacebookMarketingArgs(), options.WithDefaults());

        public static Output<GetSourceFacebookMarketingResult> Invoke(GetSourceFacebookMarketingInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSourceFacebookMarketingResult>("airbyte:index/getSourceFacebookMarketing:getSourceFacebookMarketing", args ?? new GetSourceFacebookMarketingInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSourceFacebookMarketingArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public string SourceId { get; set; } = null!;

        public GetSourceFacebookMarketingArgs()
        {
        }
        public static new GetSourceFacebookMarketingArgs Empty => new GetSourceFacebookMarketingArgs();
    }

    public sealed class GetSourceFacebookMarketingInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("sourceId", required: true)]
        public Input<string> SourceId { get; set; } = null!;

        public GetSourceFacebookMarketingInvokeArgs()
        {
        }
        public static new GetSourceFacebookMarketingInvokeArgs Empty => new GetSourceFacebookMarketingInvokeArgs();
    }


    [OutputType]
    public sealed class GetSourceFacebookMarketingResult
    {
        public readonly string Configuration;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string SourceId;
        public readonly string SourceType;
        public readonly string WorkspaceId;

        [OutputConstructor]
        private GetSourceFacebookMarketingResult(
            string configuration,

            string id,

            string name,

            string sourceId,

            string sourceType,

            string workspaceId)
        {
            Configuration = configuration;
            Id = id;
            Name = name;
            SourceId = sourceId;
            SourceType = sourceType;
            WorkspaceId = workspaceId;
        }
    }
}
