// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationDatabricksConfigurationDataSourceAmazonS3
    {
        /// <summary>
        /// The pattern allows you to set the file-name format for the S3 staging file(s)
        /// </summary>
        public readonly string? FileNamePattern;
        /// <summary>
        /// The Access Key Id granting allow one to access the above S3 staging bucket. Airbyte requires Read and Write permissions to the given bucket.
        /// </summary>
        public readonly string S3AccessKeyId;
        /// <summary>
        /// The name of the S3 bucket to use for intermittent staging of the data.
        /// </summary>
        public readonly string S3BucketName;
        /// <summary>
        /// The directory under the S3 bucket where data will be written.
        /// </summary>
        public readonly string S3BucketPath;
        /// <summary>
        /// The region of the S3 staging bucket to use if utilising a copy strategy. must be one of ["", "us-east-1", "us-east-2", "us-west-1", "us-west-2", "af-south-1", "ap-east-1", "ap-south-1", "ap-northeast-1", "ap-northeast-2", "ap-northeast-3", "ap-southeast-1", "ap-southeast-2", "ca-central-1", "cn-north-1", "cn-northwest-1", "eu-central-1", "eu-north-1", "eu-south-1", "eu-west-1", "eu-west-2", "eu-west-3", "sa-east-1", "me-south-1", "us-gov-east-1", "us-gov-west-1"]; Default: ""
        /// </summary>
        public readonly string? S3BucketRegion;
        /// <summary>
        /// The corresponding secret to the above access key id.
        /// </summary>
        public readonly string S3SecretAccessKey;

        [OutputConstructor]
        private DestinationDatabricksConfigurationDataSourceAmazonS3(
            string? fileNamePattern,

            string s3AccessKeyId,

            string s3BucketName,

            string s3BucketPath,

            string? s3BucketRegion,

            string s3SecretAccessKey)
        {
            FileNamePattern = fileNamePattern;
            S3AccessKeyId = s3AccessKeyId;
            S3BucketName = s3BucketName;
            S3BucketPath = s3BucketPath;
            S3BucketRegion = s3BucketRegion;
            S3SecretAccessKey = s3SecretAccessKey;
        }
    }
}
