// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationSnowflakeConfigurationCredentials
    {
        public readonly Outputs.DestinationSnowflakeConfigurationCredentialsKeyPairAuthentication? KeyPairAuthentication;
        public readonly Outputs.DestinationSnowflakeConfigurationCredentialsOAuth20? OAuth20;
        public readonly Outputs.DestinationSnowflakeConfigurationCredentialsUsernameAndPassword? UsernameAndPassword;

        [OutputConstructor]
        private DestinationSnowflakeConfigurationCredentials(
            Outputs.DestinationSnowflakeConfigurationCredentialsKeyPairAuthentication? keyPairAuthentication,

            Outputs.DestinationSnowflakeConfigurationCredentialsOAuth20? oAuth20,

            Outputs.DestinationSnowflakeConfigurationCredentialsUsernameAndPassword? usernameAndPassword)
        {
            KeyPairAuthentication = keyPairAuthentication;
            OAuth20 = oAuth20;
            UsernameAndPassword = usernameAndPassword;
        }
    }
}
