// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationTeradataConfigurationSslModeVerifyCa
    {
        /// <summary>
        /// Specifies the file name of a PEM file that contains Certificate Authority (CA) certificates for use with SSLMODE=verify-ca.
        ///  See more information - &lt;a href="https://teradata-docs.s3.amazonaws.com/doc/connectivity/jdbc/reference/current/jdbcug_chapter_2.html#URL_SSLCA"&gt; in the docs&lt;/a&gt;.
        /// </summary>
        public readonly string SslCaCertificate;

        [OutputConstructor]
        private DestinationTeradataConfigurationSslModeVerifyCa(string sslCaCertificate)
        {
            SslCaCertificate = sslCaCertificate;
        }
    }
}
