// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationRedshiftConfiguration
    {
        /// <summary>
        /// Name of the database.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// Disable Writing Final Tables. WARNING! The data format in _airbyte_data is likely stable but there are no guarantees that other metadata columns will remain the same in future versions. Default: false
        /// </summary>
        public readonly bool? DisableTypeDedupe;
        /// <summary>
        /// Drop tables with CASCADE. WARNING! This will delete all data in all dependent objects (views, etc.). Use with caution. This option is intended for usecases which can easily rebuild the dependent objects. Default: false
        /// </summary>
        public readonly bool? DropCascade;
        /// <summary>
        /// Host Endpoint of the Redshift Cluster (must include the cluster-id, region and end with .redshift.amazonaws.com)
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// Additional properties to pass to the JDBC URL string when connecting to the database formatted as 'key=value' pairs separated by the symbol '&amp;'. (example: key1=value1&amp;key2=value2&amp;key3=value3).
        /// </summary>
        public readonly string? JdbcUrlParams;
        /// <summary>
        /// Password associated with the username.
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// Port of the database. Default: 5439
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// The schema to write raw tables into (default: airbyte_internal).
        /// </summary>
        public readonly string? RawDataSchema;
        /// <summary>
        /// The default schema tables are written to if the source does not specify a namespace. Unless specifically configured, the usual value for this field is "public". Default: "public"
        /// </summary>
        public readonly string? Schema;
        /// <summary>
        /// Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use.
        /// </summary>
        public readonly Outputs.DestinationRedshiftConfigurationTunnelMethod? TunnelMethod;
        /// <summary>
        /// The way data will be uploaded to Redshift.
        /// </summary>
        public readonly Outputs.DestinationRedshiftConfigurationUploadingMethod? UploadingMethod;
        /// <summary>
        /// Username to use to access the database.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private DestinationRedshiftConfiguration(
            string database,

            bool? disableTypeDedupe,

            bool? dropCascade,

            string host,

            string? jdbcUrlParams,

            string password,

            int? port,

            string? rawDataSchema,

            string? schema,

            Outputs.DestinationRedshiftConfigurationTunnelMethod? tunnelMethod,

            Outputs.DestinationRedshiftConfigurationUploadingMethod? uploadingMethod,

            string username)
        {
            Database = database;
            DisableTypeDedupe = disableTypeDedupe;
            DropCascade = dropCascade;
            Host = host;
            JdbcUrlParams = jdbcUrlParams;
            Password = password;
            Port = port;
            RawDataSchema = rawDataSchema;
            Schema = schema;
            TunnelMethod = tunnelMethod;
            UploadingMethod = uploadingMethod;
            Username = username;
        }
    }
}
