// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationMssqlConfiguration
    {
        /// <summary>
        /// The name of the MSSQL database.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// The host name of the MSSQL database.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// Additional properties to pass to the JDBC URL string when connecting to the database formatted as 'key=value' pairs separated by the symbol '&amp;'. (example: key1=value1&amp;key2=value2&amp;key3=value3).
        /// </summary>
        public readonly string? JdbcUrlParams;
        /// <summary>
        /// The password associated with this username.
        /// </summary>
        public readonly string? Password;
        /// <summary>
        /// The port of the MSSQL database. Default: 1433
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// The schema to write raw tables into (default: airbyte_internal)
        /// </summary>
        public readonly string? RawDataSchema;
        /// <summary>
        /// The default schema tables are written to if the source does not specify a namespace. The usual value for this field is "public". Default: "public"
        /// </summary>
        public readonly string? Schema;
        /// <summary>
        /// The encryption method which is used to communicate with the database.
        /// </summary>
        public readonly Outputs.DestinationMssqlConfigurationSslMethod? SslMethod;
        /// <summary>
        /// Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use.
        /// </summary>
        public readonly Outputs.DestinationMssqlConfigurationTunnelMethod? TunnelMethod;
        /// <summary>
        /// The username which is used to access the database.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private DestinationMssqlConfiguration(
            string database,

            string host,

            string? jdbcUrlParams,

            string? password,

            int? port,

            string? rawDataSchema,

            string? schema,

            Outputs.DestinationMssqlConfigurationSslMethod? sslMethod,

            Outputs.DestinationMssqlConfigurationTunnelMethod? tunnelMethod,

            string username)
        {
            Database = database;
            Host = host;
            JdbcUrlParams = jdbcUrlParams;
            Password = password;
            Port = port;
            RawDataSchema = rawDataSchema;
            Schema = schema;
            SslMethod = sslMethod;
            TunnelMethod = tunnelMethod;
            Username = username;
        }
    }
}
