// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationYellowbrickConfigurationSslModeVerifyFull
    {
        /// <summary>
        /// CA certificate
        /// </summary>
        public readonly string CaCertificate;
        /// <summary>
        /// Client certificate
        /// </summary>
        public readonly string ClientCertificate;
        /// <summary>
        /// Client key
        /// </summary>
        public readonly string ClientKey;
        /// <summary>
        /// Password for keystorage. This field is optional. If you do not add it - the password will be generated automatically.
        /// </summary>
        public readonly string? ClientKeyPassword;

        [OutputConstructor]
        private DestinationYellowbrickConfigurationSslModeVerifyFull(
            string caCertificate,

            string clientCertificate,

            string clientKey,

            string? clientKeyPassword)
        {
            CaCertificate = caCertificate;
            ClientCertificate = clientCertificate;
            ClientKey = clientKey;
            ClientKeyPassword = clientKeyPassword;
        }
    }
}
