// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationS3ConfigurationFormatAvroApacheAvroCompressionCodecXz
    {
        /// <summary>
        /// must be one of ["xz"]; Default: "xz"
        /// </summary>
        public readonly string? Codec;
        /// <summary>
        /// See &lt;a href="https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/compressors/xz/XZCompressorOutputStream.html#XZCompressorOutputStream-java.io.OutputStream-int-"&gt;here&lt;/a&gt; for details. Default: 6
        /// </summary>
        public readonly int? CompressionLevel;

        [OutputConstructor]
        private DestinationS3ConfigurationFormatAvroApacheAvroCompressionCodecXz(
            string? codec,

            int? compressionLevel)
        {
            Codec = codec;
            CompressionLevel = compressionLevel;
        }
    }
}
