// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationSnowflakeCortexConfiguration
    {
        /// <summary>
        /// Embedding configuration
        /// </summary>
        public readonly Outputs.DestinationSnowflakeCortexConfigurationEmbedding Embedding;
        /// <summary>
        /// Snowflake can be used to store vector data and retrieve embeddings.
        /// </summary>
        public readonly Outputs.DestinationSnowflakeCortexConfigurationIndexing Indexing;
        /// <summary>
        /// Do not store the text that gets embedded along with the vector and the metadata in the destination. If set to true, only the vector and the metadata will be stored - in this case raw text for LLM use cases needs to be retrieved from another source. Default: false
        /// </summary>
        public readonly bool? OmitRawText;
        public readonly Outputs.DestinationSnowflakeCortexConfigurationProcessing Processing;

        [OutputConstructor]
        private DestinationSnowflakeCortexConfiguration(
            Outputs.DestinationSnowflakeCortexConfigurationEmbedding embedding,

            Outputs.DestinationSnowflakeCortexConfigurationIndexing indexing,

            bool? omitRawText,

            Outputs.DestinationSnowflakeCortexConfigurationProcessing processing)
        {
            Embedding = embedding;
            Indexing = indexing;
            OmitRawText = omitRawText;
            Processing = processing;
        }
    }
}
