// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationS3ConfigurationFormatCsvCommaSeparatedValues
    {
        /// <summary>
        /// Whether the output files should be compressed. If compression is selected, the output filename will have an extra extension (GZIP: ".csv.gz").
        /// </summary>
        public readonly Outputs.DestinationS3ConfigurationFormatCsvCommaSeparatedValuesCompression? Compression;
        /// <summary>
        /// Whether the input json data should be normalized (flattened) in the output CSV. Please refer to docs for details. must be one of ["No flattening", "Root level flattening"]; Default: "No flattening"
        /// </summary>
        public readonly string? Flattening;
        /// <summary>
        /// must be one of ["CSV"]; Default: "CSV"
        /// </summary>
        public readonly string? FormatType;

        [OutputConstructor]
        private DestinationS3ConfigurationFormatCsvCommaSeparatedValues(
            Outputs.DestinationS3ConfigurationFormatCsvCommaSeparatedValuesCompression? compression,

            string? flattening,

            string? formatType)
        {
            Compression = compression;
            Flattening = flattening;
            FormatType = formatType;
        }
    }
}
