// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationSnowflakeCortexConfigurationEmbeddingAzureOpenAi
    {
        /// <summary>
        /// The base URL for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource
        /// </summary>
        public readonly string ApiBase;
        /// <summary>
        /// The deployment for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource
        /// </summary>
        public readonly string Deployment;
        /// <summary>
        /// The API key for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource
        /// </summary>
        public readonly string OpenaiKey;

        [OutputConstructor]
        private DestinationSnowflakeCortexConfigurationEmbeddingAzureOpenAi(
            string apiBase,

            string deployment,

            string openaiKey)
        {
            ApiBase = apiBase;
            Deployment = deployment;
            OpenaiKey = openaiKey;
        }
    }
}
