// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationMongodbConfigurationInstanceTypeStandaloneMongoDbInstance
    {
        /// <summary>
        /// The Host of a Mongo database to be replicated.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// must be one of ["standalone"]; Default: "standalone"
        /// </summary>
        public readonly string? Instance;
        /// <summary>
        /// The Port of a Mongo database to be replicated. Default: 27017
        /// </summary>
        public readonly int? Port;

        [OutputConstructor]
        private DestinationMongodbConfigurationInstanceTypeStandaloneMongoDbInstance(
            string host,

            string? instance,

            int? port)
        {
            Host = host;
            Instance = instance;
            Port = port;
        }
    }
}
