// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationFirestoreConfiguration
    {
        /// <summary>
        /// The contents of the JSON service account key. Check out the &lt;a href="https://docs.airbyte.io/integrations/destinations/firestore"&gt;docs&lt;/a&gt; if you need help generating this key. Default credentials will be used if this field is left empty.
        /// </summary>
        public readonly string? CredentialsJson;
        /// <summary>
        /// The GCP project ID for the project containing the target BigQuery dataset.
        /// </summary>
        public readonly string ProjectId;

        [OutputConstructor]
        private DestinationFirestoreConfiguration(
            string? credentialsJson,

            string projectId)
        {
            CredentialsJson = credentialsJson;
            ProjectId = projectId;
        }
    }
}
