// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationSnowflakeConfigurationCredentialsKeyPairAuthentication
    {
        /// <summary>
        /// RSA Private key to use for Snowflake connection. See the &lt;a href="https://docs.airbyte.com/integrations/destinations/snowflake"&gt;docs&lt;/a&gt; for more information on how to obtain this key.
        /// </summary>
        public readonly string PrivateKey;
        /// <summary>
        /// Passphrase for private key
        /// </summary>
        public readonly string? PrivateKeyPassword;

        [OutputConstructor]
        private DestinationSnowflakeConfigurationCredentialsKeyPairAuthentication(
            string privateKey,

            string? privateKeyPassword)
        {
            PrivateKey = privateKey;
            PrivateKeyPassword = privateKeyPassword;
        }
    }
}
