// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationGcsConfigurationFormatJsonLinesNewlineDelimitedJsonCompressionNoCompression
    {
        /// <summary>
        /// must be one of ["No Compression"]; Default: "No Compression"
        /// </summary>
        public readonly string? CompressionType;

        [OutputConstructor]
        private DestinationGcsConfigurationFormatJsonLinesNewlineDelimitedJsonCompressionNoCompression(string? compressionType)
        {
            CompressionType = compressionType;
        }
    }
}
