// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationAwsDatalakeConfigurationFormatJsonLinesNewlineDelimitedJson
    {
        /// <summary>
        /// The compression algorithm used to compress data. must be one of ["UNCOMPRESSED", "GZIP"]; Default: "UNCOMPRESSED"
        /// </summary>
        public readonly string? CompressionCodec;
        /// <summary>
        /// must be one of ["JSONL"]; Default: "JSONL"
        /// </summary>
        public readonly string? FormatType;

        [OutputConstructor]
        private DestinationAwsDatalakeConfigurationFormatJsonLinesNewlineDelimitedJson(
            string? compressionCodec,

            string? formatType)
        {
            CompressionCodec = compressionCodec;
            FormatType = formatType;
        }
    }
}
