// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationWeaviateConfigurationEmbedding
    {
        /// <summary>
        /// Use the Azure-hosted OpenAI API to embed text. This option is using the text-embedding-ada-002 model with 1536 embedding dimensions.
        /// </summary>
        public readonly Outputs.DestinationWeaviateConfigurationEmbeddingAzureOpenAi? AzureOpenAi;
        /// <summary>
        /// Use the Cohere API to embed text.
        /// </summary>
        public readonly Outputs.DestinationWeaviateConfigurationEmbeddingCohere? Cohere;
        /// <summary>
        /// Use a fake embedding made out of random vectors with 1536 embedding dimensions. This is useful for testing the data pipeline without incurring any costs.
        /// </summary>
        public readonly Outputs.DestinationWeaviateConfigurationEmbeddingFake? Fake;
        /// <summary>
        /// Use a field in the record as the embedding. This is useful if you already have an embedding for your data and want to store it in the vector store.
        /// </summary>
        public readonly Outputs.DestinationWeaviateConfigurationEmbeddingFromField? FromField;
        /// <summary>
        /// Do not calculate and pass embeddings to Weaviate. Suitable for clusters with configured vectorizers to calculate embeddings within Weaviate or for classes that should only support regular text search.
        /// </summary>
        public readonly Outputs.DestinationWeaviateConfigurationEmbeddingNoExternalEmbedding? NoExternalEmbedding;
        /// <summary>
        /// Use the OpenAI API to embed text. This option is using the text-embedding-ada-002 model with 1536 embedding dimensions.
        /// </summary>
        public readonly Outputs.DestinationWeaviateConfigurationEmbeddingOpenAi? OpenAi;
        /// <summary>
        /// Use a service that's compatible with the OpenAI API to embed text.
        /// </summary>
        public readonly Outputs.DestinationWeaviateConfigurationEmbeddingOpenAiCompatible? OpenAiCompatible;

        [OutputConstructor]
        private DestinationWeaviateConfigurationEmbedding(
            Outputs.DestinationWeaviateConfigurationEmbeddingAzureOpenAi? azureOpenAi,

            Outputs.DestinationWeaviateConfigurationEmbeddingCohere? cohere,

            Outputs.DestinationWeaviateConfigurationEmbeddingFake? fake,

            Outputs.DestinationWeaviateConfigurationEmbeddingFromField? fromField,

            Outputs.DestinationWeaviateConfigurationEmbeddingNoExternalEmbedding? noExternalEmbedding,

            Outputs.DestinationWeaviateConfigurationEmbeddingOpenAi? openAi,

            Outputs.DestinationWeaviateConfigurationEmbeddingOpenAiCompatible? openAiCompatible)
        {
            AzureOpenAi = azureOpenAi;
            Cohere = cohere;
            Fake = fake;
            FromField = fromField;
            NoExternalEmbedding = noExternalEmbedding;
            OpenAi = openAi;
            OpenAiCompatible = openAiCompatible;
        }
    }
}
