// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationMongodbConfigurationInstanceTypeMongoDbAtlas
    {
        /// <summary>
        /// URL of a cluster to connect to.
        /// </summary>
        public readonly string ClusterUrl;
        /// <summary>
        /// must be one of ["atlas"]; Default: "atlas"
        /// </summary>
        public readonly string? Instance;

        [OutputConstructor]
        private DestinationMongodbConfigurationInstanceTypeMongoDbAtlas(
            string clusterUrl,

            string? instance)
        {
            ClusterUrl = clusterUrl;
            Instance = instance;
        }
    }
}
