// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class DestinationYellowbrickConfigurationSslMode
    {
        /// <summary>
        /// Allow SSL mode.
        /// </summary>
        public readonly Outputs.DestinationYellowbrickConfigurationSslModeAllow? Allow;
        /// <summary>
        /// Disable SSL.
        /// </summary>
        public readonly Outputs.DestinationYellowbrickConfigurationSslModeDisable? Disable;
        /// <summary>
        /// Prefer SSL mode.
        /// </summary>
        public readonly Outputs.DestinationYellowbrickConfigurationSslModePrefer? Prefer;
        /// <summary>
        /// Require SSL mode.
        /// </summary>
        public readonly Outputs.DestinationYellowbrickConfigurationSslModeRequire? Require;
        /// <summary>
        /// Verify-ca SSL mode.
        /// </summary>
        public readonly Outputs.DestinationYellowbrickConfigurationSslModeVerifyCa? VerifyCa;
        /// <summary>
        /// Verify-full SSL mode.
        /// </summary>
        public readonly Outputs.DestinationYellowbrickConfigurationSslModeVerifyFull? VerifyFull;

        [OutputConstructor]
        private DestinationYellowbrickConfigurationSslMode(
            Outputs.DestinationYellowbrickConfigurationSslModeAllow? allow,

            Outputs.DestinationYellowbrickConfigurationSslModeDisable? disable,

            Outputs.DestinationYellowbrickConfigurationSslModePrefer? prefer,

            Outputs.DestinationYellowbrickConfigurationSslModeRequire? require,

            Outputs.DestinationYellowbrickConfigurationSslModeVerifyCa? verifyCa,

            Outputs.DestinationYellowbrickConfigurationSslModeVerifyFull? verifyFull)
        {
            Allow = allow;
            Disable = disable;
            Prefer = prefer;
            Require = require;
            VerifyCa = verifyCa;
            VerifyFull = verifyFull;
        }
    }
}
