// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceConvexConfiguration
    {
        /// <summary>
        /// API access key used to retrieve data from Convex.
        /// </summary>
        public readonly string AccessKey;
        public readonly string DeploymentUrl;

        [OutputConstructor]
        private SourceConvexConfiguration(
            string accessKey,

            string deploymentUrl)
        {
            AccessKey = accessKey;
            DeploymentUrl = deploymentUrl;
        }
    }
}
