// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceSonarCloudConfiguration
    {
        /// <summary>
        /// Comma-separated list of component keys.
        /// </summary>
        public readonly ImmutableArray<string> ComponentKeys;
        /// <summary>
        /// To retrieve issues created before the given date (inclusive).
        /// </summary>
        public readonly string? EndDate;
        /// <summary>
        /// Organization key. See &lt;a href="https://docs.sonarcloud.io/appendices/project-information/#project-and-organization-keys"&gt;here&lt;/a&gt;.
        /// </summary>
        public readonly string Organization;
        /// <summary>
        /// To retrieve issues created after the given date (inclusive).
        /// </summary>
        public readonly string? StartDate;
        /// <summary>
        /// Your User Token. See &lt;a href="https://docs.sonarcloud.io/advanced-setup/user-accounts/"&gt;here&lt;/a&gt;. The token is case sensitive.
        /// </summary>
        public readonly string UserToken;

        [OutputConstructor]
        private SourceSonarCloudConfiguration(
            ImmutableArray<string> componentKeys,

            string? endDate,

            string organization,

            string? startDate,

            string userToken)
        {
            ComponentKeys = componentKeys;
            EndDate = endDate;
            Organization = organization;
            StartDate = startDate;
            UserToken = userToken;
        }
    }
}
