// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceAirtableConfigurationCredentialsOAuth20
    {
        /// <summary>
        /// Access Token for making authenticated requests.
        /// </summary>
        public readonly string? AccessToken;
        /// <summary>
        /// The client ID of the Airtable developer application.
        /// </summary>
        public readonly string ClientId;
        /// <summary>
        /// The client secret the Airtable developer application.
        /// </summary>
        public readonly string ClientSecret;
        /// <summary>
        /// The key to refresh the expired access token.
        /// </summary>
        public readonly string RefreshToken;
        /// <summary>
        /// The date-time when the access token should be refreshed.
        /// </summary>
        public readonly string? TokenExpiryDate;

        [OutputConstructor]
        private SourceAirtableConfigurationCredentialsOAuth20(
            string? accessToken,

            string clientId,

            string clientSecret,

            string refreshToken,

            string? tokenExpiryDate)
        {
            AccessToken = accessToken;
            ClientId = clientId;
            ClientSecret = clientSecret;
            RefreshToken = refreshToken;
            TokenExpiryDate = tokenExpiryDate;
        }
    }
}
