// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceSnowflakeConfigurationCredentials
    {
        public readonly Outputs.SourceSnowflakeConfigurationCredentialsOAuth20? OAuth20;
        public readonly Outputs.SourceSnowflakeConfigurationCredentialsUsernameAndPassword? UsernameAndPassword;

        [OutputConstructor]
        private SourceSnowflakeConfigurationCredentials(
            Outputs.SourceSnowflakeConfigurationCredentialsOAuth20? oAuth20,

            Outputs.SourceSnowflakeConfigurationCredentialsUsernameAndPassword? usernameAndPassword)
        {
            OAuth20 = oAuth20;
            UsernameAndPassword = usernameAndPassword;
        }
    }
}
