// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceGetlagoConfiguration
    {
        /// <summary>
        /// Your API Key. See &lt;a href="https://doc.getlago.com/docs/api/intro"&gt;here&lt;/a&gt;.
        /// </summary>
        public readonly string ApiKey;
        /// <summary>
        /// Your Lago API URL. Default: "https://api.getlago.com/api/v1"
        /// </summary>
        public readonly string? ApiUrl;

        [OutputConstructor]
        private SourceGetlagoConfiguration(
            string apiKey,

            string? apiUrl)
        {
            ApiKey = apiKey;
            ApiUrl = apiUrl;
        }
    }
}
