// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceFireboltConfiguration
    {
        /// <summary>
        /// Firebolt account to login.
        /// </summary>
        public readonly string Account;
        /// <summary>
        /// Firebolt service account ID.
        /// </summary>
        public readonly string ClientId;
        /// <summary>
        /// Firebolt secret, corresponding to the service account ID.
        /// </summary>
        public readonly string ClientSecret;
        /// <summary>
        /// The database to connect to.
        /// </summary>
        public readonly string Database;
        /// <summary>
        /// Engine name to connect to.
        /// </summary>
        public readonly string Engine;
        /// <summary>
        /// The host name of your Firebolt database.
        /// </summary>
        public readonly string? Host;

        [OutputConstructor]
        private SourceFireboltConfiguration(
            string account,

            string clientId,

            string clientSecret,

            string database,

            string engine,

            string? host)
        {
            Account = account;
            ClientId = clientId;
            ClientSecret = clientSecret;
            Database = database;
            Engine = engine;
            Host = host;
        }
    }
}
