// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceFacebookMarketingConfiguration
    {
        /// <summary>
        /// The value of the generated access token. From your App’s Dashboard, click on "Marketing API" then "Tools". Select permissions &lt;b&gt;ads_management, ads_read, read_insights, business_management&lt;/b&gt;. Then click on "Get token". See the &lt;a href="https://docs.airbyte.com/integrations/sources/facebook-marketing"&gt;docs&lt;/a&gt; for more information.
        /// </summary>
        public readonly string AccessToken;
        /// <summary>
        /// The Facebook Ad account ID(s) to pull data from. The Ad account ID number is in the account dropdown menu or in your browser's address bar of your &lt;a href="https://adsmanager.facebook.com/adsmanager/"&gt;Meta Ads Manager&lt;/a&gt;. See the &lt;a href="https://www.facebook.com/business/help/1492627900875762"&gt;docs&lt;/a&gt; for more information.
        /// </summary>
        public readonly ImmutableArray<string> AccountIds;
        /// <summary>
        /// Allows action_breakdowns to be an empty list. Default: true
        /// </summary>
        public readonly bool? ActionBreakdownsAllowEmpty;
        /// <summary>
        /// Select the statuses you want to be loaded in the stream. If no specific statuses are selected, the API's default behavior applies, and some statuses may be filtered out.
        /// </summary>
        public readonly ImmutableArray<string> AdStatuses;
        /// <summary>
        /// Select the statuses you want to be loaded in the stream. If no specific statuses are selected, the API's default behavior applies, and some statuses may be filtered out.
        /// </summary>
        public readonly ImmutableArray<string> AdsetStatuses;
        /// <summary>
        /// Select the statuses you want to be loaded in the stream. If no specific statuses are selected, the API's default behavior applies, and some statuses may be filtered out.
        /// </summary>
        public readonly ImmutableArray<string> CampaignStatuses;
        /// <summary>
        /// The Client Id for your OAuth app
        /// </summary>
        public readonly string? ClientId;
        /// <summary>
        /// The Client Secret for your OAuth app
        /// </summary>
        public readonly string? ClientSecret;
        /// <summary>
        /// A list which contains ad statistics entries, each entry must have a name and can contains fields, breakdowns or action_breakdowns. Click on "add" to fill this field.
        /// </summary>
        public readonly ImmutableArray<Outputs.SourceFacebookMarketingConfigurationCustomInsight> CustomInsights;
        /// <summary>
        /// The date until which you'd like to replicate data for all incremental streams, in the format YYYY-MM-DDT00:00:00Z. All data generated between the start date and this end date will be replicated. Not setting this option will result in always syncing the latest data.
        /// </summary>
        public readonly string? EndDate;
        /// <summary>
        /// Set to active if you want to fetch the thumbnail_url and store the result in thumbnail_data_url for each Ad Creative. Default: false
        /// </summary>
        public readonly bool? FetchThumbnailImages;
        /// <summary>
        /// Insights Job Timeout establishes the maximum amount of time (in minutes) of waiting for the report job to complete. When timeout is reached the job is considered failed and we are trying to request smaller amount of data by breaking the job to few smaller ones. If you definitely know that 60 minutes is not enough for your report to be processed then you can decrease the timeout value, so we start breaking job to smaller parts faster. Default: 60
        /// </summary>
        public readonly int? InsightsJobTimeout;
        /// <summary>
        /// The attribution window. Facebook freezes insight data 28 days after it was generated, which means that all data from the past 28 days may have changed since we last emitted it, so you can retrieve refreshed insights from the past by setting this parameter. If you set a custom lookback window value in Facebook account, please provide the same value here. Default: 28
        /// </summary>
        public readonly int? InsightsLookbackWindow;
        /// <summary>
        /// Page size used when sending requests to Facebook API to specify number of records per page when response has pagination. Most users do not need to set this field unless they specifically need to tune the connector to address specific issues or use cases. Default: 100
        /// </summary>
        public readonly int? PageSize;
        /// <summary>
        /// The date from which you'd like to replicate data for all incremental streams, in the format YYYY-MM-DDT00:00:00Z. If not set then all data will be replicated for usual streams and only last 2 years for insight streams.
        /// </summary>
        public readonly string? StartDate;

        [OutputConstructor]
        private SourceFacebookMarketingConfiguration(
            string accessToken,

            ImmutableArray<string> accountIds,

            bool? actionBreakdownsAllowEmpty,

            ImmutableArray<string> adStatuses,

            ImmutableArray<string> adsetStatuses,

            ImmutableArray<string> campaignStatuses,

            string? clientId,

            string? clientSecret,

            ImmutableArray<Outputs.SourceFacebookMarketingConfigurationCustomInsight> customInsights,

            string? endDate,

            bool? fetchThumbnailImages,

            int? insightsJobTimeout,

            int? insightsLookbackWindow,

            int? pageSize,

            string? startDate)
        {
            AccessToken = accessToken;
            AccountIds = accountIds;
            ActionBreakdownsAllowEmpty = actionBreakdownsAllowEmpty;
            AdStatuses = adStatuses;
            AdsetStatuses = adsetStatuses;
            CampaignStatuses = campaignStatuses;
            ClientId = clientId;
            ClientSecret = clientSecret;
            CustomInsights = customInsights;
            EndDate = endDate;
            FetchThumbnailImages = fetchThumbnailImages;
            InsightsJobTimeout = insightsJobTimeout;
            InsightsLookbackWindow = insightsLookbackWindow;
            PageSize = pageSize;
            StartDate = startDate;
        }
    }
}
