// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourcePosthogConfiguration
    {
        /// <summary>
        /// API Key. See the &lt;a href="https://docs.airbyte.com/integrations/sources/posthog"&gt;docs&lt;/a&gt; for information on how to generate this key.
        /// </summary>
        public readonly string ApiKey;
        /// <summary>
        /// Base PostHog url. Defaults to PostHog Cloud (https://app.posthog.com). Default: "https://app.posthog.com"
        /// </summary>
        public readonly string? BaseUrl;
        /// <summary>
        /// Set lower value in case of failing long running sync of events stream. Default: 30
        /// </summary>
        public readonly int? EventsTimeStep;
        /// <summary>
        /// The date from which you'd like to replicate the data. Any data before this date will not be replicated.
        /// </summary>
        public readonly string StartDate;

        [OutputConstructor]
        private SourcePosthogConfiguration(
            string apiKey,

            string? baseUrl,

            int? eventsTimeStep,

            string startDate)
        {
            ApiKey = apiKey;
            BaseUrl = baseUrl;
            EventsTimeStep = eventsTimeStep;
            StartDate = startDate;
        }
    }
}
