// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceTwilioConfiguration
    {
        /// <summary>
        /// Twilio account SID
        /// </summary>
        public readonly string AccountSid;
        /// <summary>
        /// Twilio Auth Token.
        /// </summary>
        public readonly string AuthToken;
        /// <summary>
        /// How far into the past to look for records. (in minutes). Default: 0
        /// </summary>
        public readonly int? LookbackWindow;
        /// <summary>
        /// UTC date and time in the format 2020-10-01T00:00:00Z. Any data before this date will not be replicated.
        /// </summary>
        public readonly string StartDate;

        [OutputConstructor]
        private SourceTwilioConfiguration(
            string accountSid,

            string authToken,

            int? lookbackWindow,

            string startDate)
        {
            AccountSid = accountSid;
            AuthToken = authToken;
            LookbackWindow = lookbackWindow;
            StartDate = startDate;
        }
    }
}
