// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceChartmogulConfiguration
    {
        /// <summary>
        /// Your Chartmogul API key. See &lt;a href="https://help.chartmogul.com/hc/en-us/articles/4407796325906-Creating-and-Managing-API-keys#creating-an-api-key"&gt; the docs &lt;/a&gt; for info on how to obtain this.
        /// </summary>
        public readonly string ApiKey;
        /// <summary>
        /// UTC date and time in the format 2017-01-25T00:00:00Z. When feasible, any data before this date will not be replicated.
        /// </summary>
        public readonly string StartDate;

        [OutputConstructor]
        private SourceChartmogulConfiguration(
            string apiKey,

            string startDate)
        {
            ApiKey = apiKey;
            StartDate = startDate;
        }
    }
}
