// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceMicrosoftOnedriveConfigurationCredentialsServiceKeyAuthentication
    {
        /// <summary>
        /// Client ID of your Microsoft developer application
        /// </summary>
        public readonly string ClientId;
        /// <summary>
        /// Client Secret of your Microsoft developer application
        /// </summary>
        public readonly string ClientSecret;
        /// <summary>
        /// Tenant ID of the Microsoft OneDrive user
        /// </summary>
        public readonly string TenantId;
        /// <summary>
        /// Special characters such as a period, comma, space, and the at sign (@) are converted to underscores (_). More details: https://learn.microsoft.com/en-us/sharepoint/list-onedrive-urls
        /// </summary>
        public readonly string UserPrincipalName;

        [OutputConstructor]
        private SourceMicrosoftOnedriveConfigurationCredentialsServiceKeyAuthentication(
            string clientId,

            string clientSecret,

            string tenantId,

            string userPrincipalName)
        {
            ClientId = clientId;
            ClientSecret = clientSecret;
            TenantId = tenantId;
            UserPrincipalName = userPrincipalName;
        }
    }
}
