// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceGoogleAdsConfiguration
    {
        /// <summary>
        /// A conversion window is the number of days after an ad interaction (such as an ad click or video view) during which a conversion, such as a purchase, is recorded in Google Ads. For more information, see &lt;a href="https://support.google.com/google-ads/answer/3123169?hl=en"&gt;Google's documentation&lt;/a&gt;. Default: 14
        /// </summary>
        public readonly int? ConversionWindowDays;
        public readonly Outputs.SourceGoogleAdsConfigurationCredentials Credentials;
        public readonly ImmutableArray<Outputs.SourceGoogleAdsConfigurationCustomQueriesArray> CustomQueriesArrays;
        /// <summary>
        /// Comma-separated list of (client) customer IDs. Each customer ID must be specified as a 10-digit number without dashes. For detailed instructions on finding this value, refer to our &lt;a href="https://docs.airbyte.com/integrations/sources/google-ads#setup-guide"&gt;documentation&lt;/a&gt;.
        /// </summary>
        public readonly string? CustomerId;
        /// <summary>
        /// A list of customer statuses to filter on. For detailed info about what each status mean refer to Google Ads &lt;a href="https://developers.google.com/google-ads/api/reference/rpc/v15/CustomerStatusEnum.CustomerStatus"&gt;documentation&lt;/a&gt;.
        /// </summary>
        public readonly ImmutableArray<string> CustomerStatusFilters;
        /// <summary>
        /// UTC date in the format YYYY-MM-DD. Any data after this date will not be replicated. (Default value of today is used if not set)
        /// </summary>
        public readonly string? EndDate;
        /// <summary>
        /// UTC date in the format YYYY-MM-DD. Any data before this date will not be replicated. (Default value of two years ago is used if not set)
        /// </summary>
        public readonly string? StartDate;

        [OutputConstructor]
        private SourceGoogleAdsConfiguration(
            int? conversionWindowDays,

            Outputs.SourceGoogleAdsConfigurationCredentials credentials,

            ImmutableArray<Outputs.SourceGoogleAdsConfigurationCustomQueriesArray> customQueriesArrays,

            string? customerId,

            ImmutableArray<string> customerStatusFilters,

            string? endDate,

            string? startDate)
        {
            ConversionWindowDays = conversionWindowDays;
            Credentials = credentials;
            CustomQueriesArrays = customQueriesArrays;
            CustomerId = customerId;
            CustomerStatusFilters = customerStatusFilters;
            EndDate = endDate;
            StartDate = startDate;
        }
    }
}
