// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceHubspotConfigurationCredentialsPrivateApp
    {
        /// <summary>
        /// HubSpot Access token. See the &lt;a href="https://developers.hubspot.com/docs/api/private-apps"&gt;Hubspot docs&lt;/a&gt; if you need help finding this token.
        /// </summary>
        public readonly string AccessToken;

        [OutputConstructor]
        private SourceHubspotConfigurationCredentialsPrivateApp(string accessToken)
        {
            AccessToken = accessToken;
        }
    }
}
