// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourcePersistiqConfiguration
    {
        /// <summary>
        /// PersistIq API Key. See the &lt;a href="https://apidocs.persistiq.com/#authentication"&gt;docs&lt;/a&gt; for more information on where to find that key.
        /// </summary>
        public readonly string ApiKey;

        [OutputConstructor]
        private SourcePersistiqConfiguration(string apiKey)
        {
            ApiKey = apiKey;
        }
    }
}
