// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceGoogleDirectoryConfigurationCredentialsServiceAccountKey
    {
        /// <summary>
        /// The contents of the JSON service account key. See the &lt;a href="https://developers.google.com/admin-sdk/directory/v1/guides/delegation"&gt;docs&lt;/a&gt; for more information on how to generate this key.
        /// </summary>
        public readonly string CredentialsJson;
        /// <summary>
        /// The email of the user, which has permissions to access the Google Workspace Admin APIs.
        /// </summary>
        public readonly string Email;

        [OutputConstructor]
        private SourceGoogleDirectoryConfigurationCredentialsServiceAccountKey(
            string credentialsJson,

            string email)
        {
            CredentialsJson = credentialsJson;
            Email = email;
        }
    }
}
