// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceMicrosoftOnedriveConfigurationStreamFormatParquetFormat
    {
        /// <summary>
        /// Whether to convert decimal fields to floats. There is a loss of precision when converting decimals to floats, so this is not recommended. Default: false
        /// </summary>
        public readonly bool? DecimalAsFloat;

        [OutputConstructor]
        private SourceMicrosoftOnedriveConfigurationStreamFormatParquetFormat(bool? decimalAsFloat)
        {
            DecimalAsFloat = decimalAsFloat;
        }
    }
}
