// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceGoogleDriveConfiguration
    {
        /// <summary>
        /// Credentials for connecting to the Google Drive API
        /// </summary>
        public readonly Outputs.SourceGoogleDriveConfigurationCredentials Credentials;
        /// <summary>
        /// URL for the folder you want to sync. Using individual streams and glob patterns, it's possible to only sync a subset of all files located in the folder.
        /// </summary>
        public readonly string FolderUrl;
        /// <summary>
        /// UTC date and time in the format 2017-01-25T00:00:00.000000Z. Any file modified before this date will not be replicated.
        /// </summary>
        public readonly string? StartDate;
        /// <summary>
        /// Each instance of this configuration defines a &lt;a href="https://docs.airbyte.com/cloud/core-concepts#stream"&gt;stream&lt;/a&gt;. Use this to define which files belong in the stream, their format, and how they should be parsed and validated. When sending data to warehouse destination such as Snowflake or BigQuery, each stream is a separate table.
        /// </summary>
        public readonly ImmutableArray<Outputs.SourceGoogleDriveConfigurationStream> Streams;

        [OutputConstructor]
        private SourceGoogleDriveConfiguration(
            Outputs.SourceGoogleDriveConfigurationCredentials credentials,

            string folderUrl,

            string? startDate,

            ImmutableArray<Outputs.SourceGoogleDriveConfigurationStream> streams)
        {
            Credentials = credentials;
            FolderUrl = folderUrl;
            StartDate = startDate;
            Streams = streams;
        }
    }
}
