// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceOktaConfiguration
    {
        public readonly Outputs.SourceOktaConfigurationCredentials? Credentials;
        /// <summary>
        /// The Okta domain. See the &lt;a href="https://docs.airbyte.com/integrations/sources/okta"&gt;docs&lt;/a&gt; for instructions on how to find it.
        /// </summary>
        public readonly string? Domain;
        /// <summary>
        /// UTC date and time in the format YYYY-MM-DDTHH:MM:SSZ. Any data before this date will not be replicated.
        /// </summary>
        public readonly string? StartDate;

        [OutputConstructor]
        private SourceOktaConfiguration(
            Outputs.SourceOktaConfigurationCredentials? credentials,

            string? domain,

            string? startDate)
        {
            Credentials = credentials;
            Domain = domain;
            StartDate = startDate;
        }
    }
}
