// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceFaunaConfiguration
    {
        /// <summary>
        /// Settings for the Fauna Collection.
        /// </summary>
        public readonly Outputs.SourceFaunaConfigurationCollection? Collection;
        /// <summary>
        /// Domain of Fauna to query. Defaults db.fauna.com. See &lt;a href=https://docs.fauna.com/fauna/current/learn/understanding/region_groups#how-to-use-region-groups&gt;the docs&lt;/a&gt;. Default: "db.fauna.com"
        /// </summary>
        public readonly string? Domain;
        /// <summary>
        /// Endpoint port. Default: 443
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// URL scheme. Default: "https"
        /// </summary>
        public readonly string? Scheme;
        /// <summary>
        /// Fauna secret, used when authenticating with the database.
        /// </summary>
        public readonly string Secret;

        [OutputConstructor]
        private SourceFaunaConfiguration(
            Outputs.SourceFaunaConfigurationCollection? collection,

            string? domain,

            int? port,

            string? scheme,

            string secret)
        {
            Collection = collection;
            Domain = domain;
            Port = port;
            Scheme = scheme;
            Secret = secret;
        }
    }
}
