// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceShopifyConfigurationCredentials
    {
        /// <summary>
        /// API Password Auth
        /// </summary>
        public readonly Outputs.SourceShopifyConfigurationCredentialsApiPassword? ApiPassword;
        /// <summary>
        /// OAuth2.0
        /// </summary>
        public readonly Outputs.SourceShopifyConfigurationCredentialsOAuth20? OAuth20;

        [OutputConstructor]
        private SourceShopifyConfigurationCredentials(
            Outputs.SourceShopifyConfigurationCredentialsApiPassword? apiPassword,

            Outputs.SourceShopifyConfigurationCredentialsOAuth20? oAuth20)
        {
            ApiPassword = apiPassword;
            OAuth20 = oAuth20;
        }
    }
}
