// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceEmailoctopusConfiguration
    {
        /// <summary>
        /// EmailOctopus API Key. See the &lt;a href="https://help.emailoctopus.com/article/165-how-to-create-and-delete-api-keys"&gt;docs&lt;/a&gt; for information on how to generate this key.
        /// </summary>
        public readonly string ApiKey;

        [OutputConstructor]
        private SourceEmailoctopusConfiguration(string apiKey)
        {
            ApiKey = apiKey;
        }
    }
}
