// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceSquareConfiguration
    {
        /// <summary>
        /// Choose how to authenticate to Square.
        /// </summary>
        public readonly Outputs.SourceSquareConfigurationCredentials? Credentials;
        /// <summary>
        /// In some streams there is an option to include deleted objects (Items, Categories, Discounts, Taxes). Default: false
        /// </summary>
        public readonly bool? IncludeDeletedObjects;
        /// <summary>
        /// Determines whether to use the sandbox or production environment. Default: false
        /// </summary>
        public readonly bool? IsSandbox;
        /// <summary>
        /// UTC date in the format YYYY-MM-DD. Any data before this date will not be replicated. If not set, all data will be replicated. Default: "2021-01-01"
        /// </summary>
        public readonly string? StartDate;

        [OutputConstructor]
        private SourceSquareConfiguration(
            Outputs.SourceSquareConfigurationCredentials? credentials,

            bool? includeDeletedObjects,

            bool? isSandbox,

            string? startDate)
        {
            Credentials = credentials;
            IncludeDeletedObjects = includeDeletedObjects;
            IsSandbox = isSandbox;
            StartDate = startDate;
        }
    }
}
