// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceNotionConfigurationCredentialsAccessToken
    {
        /// <summary>
        /// The Access Token for your private Notion integration. See the &lt;a href='https://docs.airbyte.com/integrations/sources/notion#step-1-create-an-integration-in-notion'&gt;docs&lt;/a&gt; for more information on how to obtain this token.
        /// </summary>
        public readonly string Token;

        [OutputConstructor]
        private SourceNotionConfigurationCredentialsAccessToken(string token)
        {
            Token = token;
        }
    }
}
