// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceMixpanelConfiguration
    {
        /// <summary>
        /// A period of time for attributing results to ads and the lookback period after those actions occur during which ad results are counted. Default attribution window is 5 days. (This value should be non-negative integer). Default: 5
        /// </summary>
        public readonly int? AttributionWindow;
        /// <summary>
        /// Choose how to authenticate to Mixpanel
        /// </summary>
        public readonly Outputs.SourceMixpanelConfigurationCredentials Credentials;
        /// <summary>
        /// Defines window size in days, that used to slice through data. You can reduce it, if amount of data in each window is too big for your environment. (This value should be positive integer). Default: 30
        /// </summary>
        public readonly int? DateWindowSize;
        /// <summary>
        /// The date in the format YYYY-MM-DD. Any data after this date will not be replicated. Left empty to always sync to most recent date
        /// </summary>
        public readonly string? EndDate;
        /// <summary>
        /// Time zone in which integer date times are stored. The project timezone may be found in the project settings in the &lt;a href="https://help.mixpanel.com/hc/en-us/articles/115004547203-Manage-Timezones-for-Projects-in-Mixpanel"&gt;Mixpanel console&lt;/a&gt;. Default: "US/Pacific"
        /// </summary>
        public readonly string? ProjectTimezone;
        /// <summary>
        /// The region of mixpanel domain instance either US or EU. must be one of ["US", "EU"]; Default: "US"
        /// </summary>
        public readonly string? Region;
        /// <summary>
        /// Setting this config parameter to TRUE ensures that new properties on events and engage records are captured. Otherwise new properties will be ignored. Default: true
        /// </summary>
        public readonly bool? SelectPropertiesByDefault;
        /// <summary>
        /// The date in the format YYYY-MM-DD. Any data before this date will not be replicated. If this option is not set, the connector will replicate data from up to one year ago by default.
        /// </summary>
        public readonly string? StartDate;

        [OutputConstructor]
        private SourceMixpanelConfiguration(
            int? attributionWindow,

            Outputs.SourceMixpanelConfigurationCredentials credentials,

            int? dateWindowSize,

            string? endDate,

            string? projectTimezone,

            string? region,

            bool? selectPropertiesByDefault,

            string? startDate)
        {
            AttributionWindow = attributionWindow;
            Credentials = credentials;
            DateWindowSize = dateWindowSize;
            EndDate = endDate;
            ProjectTimezone = projectTimezone;
            Region = region;
            SelectPropertiesByDefault = selectPropertiesByDefault;
            StartDate = startDate;
        }
    }
}
