// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceMixpanelConfigurationCredentialsServiceAccount
    {
        /// <summary>
        /// Your project ID number. See the &lt;a href="https://help.mixpanel.com/hc/en-us/articles/115004490503-Project-Settings#project-id"&gt;docs&lt;/a&gt; for more information on how to obtain this.
        /// </summary>
        public readonly int ProjectId;
        /// <summary>
        /// Mixpanel Service Account Secret. See the &lt;a href="https://developer.mixpanel.com/reference/service-accounts"&gt;docs&lt;/a&gt; for more information on how to obtain this.
        /// </summary>
        public readonly string Secret;
        /// <summary>
        /// Mixpanel Service Account Username. See the &lt;a href="https://developer.mixpanel.com/reference/service-accounts"&gt;docs&lt;/a&gt; for more information on how to obtain this.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private SourceMixpanelConfigurationCredentialsServiceAccount(
            int projectId,

            string secret,

            string username)
        {
            ProjectId = projectId;
            Secret = secret;
            Username = username;
        }
    }
}
