// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Outputs
{

    [OutputType]
    public sealed class SourceGithubConfigurationCredentialsOAuth
    {
        /// <summary>
        /// OAuth access token
        /// </summary>
        public readonly string AccessToken;
        /// <summary>
        /// OAuth Client Id
        /// </summary>
        public readonly string? ClientId;
        /// <summary>
        /// OAuth Client secret
        /// </summary>
        public readonly string? ClientSecret;

        [OutputConstructor]
        private SourceGithubConfigurationCredentialsOAuth(
            string accessToken,

            string? clientId,

            string? clientSecret)
        {
            AccessToken = accessToken;
            ClientId = clientId;
            ClientSecret = clientSecret;
        }
    }
}
