// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDestinationMssql(ctx *pulumi.Context, args *LookupDestinationMssqlArgs, opts ...pulumi.InvokeOption) (*LookupDestinationMssqlResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDestinationMssqlResult
	err := ctx.Invoke("airbyte:index/getDestinationMssql:getDestinationMssql", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDestinationMssql.
type LookupDestinationMssqlArgs struct {
	DestinationId string `pulumi:"destinationId"`
}

// A collection of values returned by getDestinationMssql.
type LookupDestinationMssqlResult struct {
	Configuration   string `pulumi:"configuration"`
	DestinationId   string `pulumi:"destinationId"`
	DestinationType string `pulumi:"destinationType"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupDestinationMssqlOutput(ctx *pulumi.Context, args LookupDestinationMssqlOutputArgs, opts ...pulumi.InvokeOption) LookupDestinationMssqlResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDestinationMssqlResult, error) {
			args := v.(LookupDestinationMssqlArgs)
			r, err := LookupDestinationMssql(ctx, &args, opts...)
			var s LookupDestinationMssqlResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupDestinationMssqlResultOutput)
}

// A collection of arguments for invoking getDestinationMssql.
type LookupDestinationMssqlOutputArgs struct {
	DestinationId pulumi.StringInput `pulumi:"destinationId"`
}

func (LookupDestinationMssqlOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDestinationMssqlArgs)(nil)).Elem()
}

// A collection of values returned by getDestinationMssql.
type LookupDestinationMssqlResultOutput struct{ *pulumi.OutputState }

func (LookupDestinationMssqlResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDestinationMssqlResult)(nil)).Elem()
}

func (o LookupDestinationMssqlResultOutput) ToLookupDestinationMssqlResultOutput() LookupDestinationMssqlResultOutput {
	return o
}

func (o LookupDestinationMssqlResultOutput) ToLookupDestinationMssqlResultOutputWithContext(ctx context.Context) LookupDestinationMssqlResultOutput {
	return o
}

func (o LookupDestinationMssqlResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationMssqlResult) string { return v.Configuration }).(pulumi.StringOutput)
}

func (o LookupDestinationMssqlResultOutput) DestinationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationMssqlResult) string { return v.DestinationId }).(pulumi.StringOutput)
}

func (o LookupDestinationMssqlResultOutput) DestinationType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationMssqlResult) string { return v.DestinationType }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupDestinationMssqlResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationMssqlResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDestinationMssqlResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationMssqlResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupDestinationMssqlResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationMssqlResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDestinationMssqlResultOutput{})
}
