// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDestinationDatabricks(ctx *pulumi.Context, args *LookupDestinationDatabricksArgs, opts ...pulumi.InvokeOption) (*LookupDestinationDatabricksResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDestinationDatabricksResult
	err := ctx.Invoke("airbyte:index/getDestinationDatabricks:getDestinationDatabricks", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDestinationDatabricks.
type LookupDestinationDatabricksArgs struct {
	DestinationId string `pulumi:"destinationId"`
}

// A collection of values returned by getDestinationDatabricks.
type LookupDestinationDatabricksResult struct {
	Configuration   string `pulumi:"configuration"`
	DestinationId   string `pulumi:"destinationId"`
	DestinationType string `pulumi:"destinationType"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupDestinationDatabricksOutput(ctx *pulumi.Context, args LookupDestinationDatabricksOutputArgs, opts ...pulumi.InvokeOption) LookupDestinationDatabricksResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDestinationDatabricksResult, error) {
			args := v.(LookupDestinationDatabricksArgs)
			r, err := LookupDestinationDatabricks(ctx, &args, opts...)
			var s LookupDestinationDatabricksResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupDestinationDatabricksResultOutput)
}

// A collection of arguments for invoking getDestinationDatabricks.
type LookupDestinationDatabricksOutputArgs struct {
	DestinationId pulumi.StringInput `pulumi:"destinationId"`
}

func (LookupDestinationDatabricksOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDestinationDatabricksArgs)(nil)).Elem()
}

// A collection of values returned by getDestinationDatabricks.
type LookupDestinationDatabricksResultOutput struct{ *pulumi.OutputState }

func (LookupDestinationDatabricksResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDestinationDatabricksResult)(nil)).Elem()
}

func (o LookupDestinationDatabricksResultOutput) ToLookupDestinationDatabricksResultOutput() LookupDestinationDatabricksResultOutput {
	return o
}

func (o LookupDestinationDatabricksResultOutput) ToLookupDestinationDatabricksResultOutputWithContext(ctx context.Context) LookupDestinationDatabricksResultOutput {
	return o
}

func (o LookupDestinationDatabricksResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationDatabricksResult) string { return v.Configuration }).(pulumi.StringOutput)
}

func (o LookupDestinationDatabricksResultOutput) DestinationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationDatabricksResult) string { return v.DestinationId }).(pulumi.StringOutput)
}

func (o LookupDestinationDatabricksResultOutput) DestinationType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationDatabricksResult) string { return v.DestinationType }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupDestinationDatabricksResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationDatabricksResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDestinationDatabricksResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationDatabricksResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupDestinationDatabricksResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDestinationDatabricksResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDestinationDatabricksResultOutput{})
}
