// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSourcePipedrive(ctx *pulumi.Context, args *LookupSourcePipedriveArgs, opts ...pulumi.InvokeOption) (*LookupSourcePipedriveResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourcePipedriveResult
	err := ctx.Invoke("airbyte:index/getSourcePipedrive:getSourcePipedrive", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourcePipedrive.
type LookupSourcePipedriveArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourcePipedrive.
type LookupSourcePipedriveResult struct {
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourcePipedriveOutput(ctx *pulumi.Context, args LookupSourcePipedriveOutputArgs, opts ...pulumi.InvokeOption) LookupSourcePipedriveResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourcePipedriveResult, error) {
			args := v.(LookupSourcePipedriveArgs)
			r, err := LookupSourcePipedrive(ctx, &args, opts...)
			var s LookupSourcePipedriveResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourcePipedriveResultOutput)
}

// A collection of arguments for invoking getSourcePipedrive.
type LookupSourcePipedriveOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourcePipedriveOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourcePipedriveArgs)(nil)).Elem()
}

// A collection of values returned by getSourcePipedrive.
type LookupSourcePipedriveResultOutput struct{ *pulumi.OutputState }

func (LookupSourcePipedriveResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourcePipedriveResult)(nil)).Elem()
}

func (o LookupSourcePipedriveResultOutput) ToLookupSourcePipedriveResultOutput() LookupSourcePipedriveResultOutput {
	return o
}

func (o LookupSourcePipedriveResultOutput) ToLookupSourcePipedriveResultOutputWithContext(ctx context.Context) LookupSourcePipedriveResultOutput {
	return o
}

func (o LookupSourcePipedriveResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePipedriveResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourcePipedriveResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePipedriveResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourcePipedriveResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePipedriveResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourcePipedriveResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePipedriveResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourcePipedriveResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePipedriveResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourcePipedriveResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePipedriveResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourcePipedriveResultOutput{})
}
