// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSourceSecoda(ctx *pulumi.Context, args *LookupSourceSecodaArgs, opts ...pulumi.InvokeOption) (*LookupSourceSecodaResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceSecodaResult
	err := ctx.Invoke("airbyte:index/getSourceSecoda:getSourceSecoda", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceSecoda.
type LookupSourceSecodaArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceSecoda.
type LookupSourceSecodaResult struct {
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceSecodaOutput(ctx *pulumi.Context, args LookupSourceSecodaOutputArgs, opts ...pulumi.InvokeOption) LookupSourceSecodaResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceSecodaResult, error) {
			args := v.(LookupSourceSecodaArgs)
			r, err := LookupSourceSecoda(ctx, &args, opts...)
			var s LookupSourceSecodaResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceSecodaResultOutput)
}

// A collection of arguments for invoking getSourceSecoda.
type LookupSourceSecodaOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceSecodaOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceSecodaArgs)(nil)).Elem()
}

// A collection of values returned by getSourceSecoda.
type LookupSourceSecodaResultOutput struct{ *pulumi.OutputState }

func (LookupSourceSecodaResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceSecodaResult)(nil)).Elem()
}

func (o LookupSourceSecodaResultOutput) ToLookupSourceSecodaResultOutput() LookupSourceSecodaResultOutput {
	return o
}

func (o LookupSourceSecodaResultOutput) ToLookupSourceSecodaResultOutputWithContext(ctx context.Context) LookupSourceSecodaResultOutput {
	return o
}

func (o LookupSourceSecodaResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSecodaResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceSecodaResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSecodaResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceSecodaResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSecodaResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceSecodaResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSecodaResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceSecodaResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSecodaResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceSecodaResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceSecodaResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceSecodaResultOutput{})
}
