// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSourceAha(ctx *pulumi.Context, args *LookupSourceAhaArgs, opts ...pulumi.InvokeOption) (*LookupSourceAhaResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceAhaResult
	err := ctx.Invoke("airbyte:index/getSourceAha:getSourceAha", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceAha.
type LookupSourceAhaArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceAha.
type LookupSourceAhaResult struct {
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceAhaOutput(ctx *pulumi.Context, args LookupSourceAhaOutputArgs, opts ...pulumi.InvokeOption) LookupSourceAhaResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceAhaResult, error) {
			args := v.(LookupSourceAhaArgs)
			r, err := LookupSourceAha(ctx, &args, opts...)
			var s LookupSourceAhaResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceAhaResultOutput)
}

// A collection of arguments for invoking getSourceAha.
type LookupSourceAhaOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceAhaOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceAhaArgs)(nil)).Elem()
}

// A collection of values returned by getSourceAha.
type LookupSourceAhaResultOutput struct{ *pulumi.OutputState }

func (LookupSourceAhaResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceAhaResult)(nil)).Elem()
}

func (o LookupSourceAhaResultOutput) ToLookupSourceAhaResultOutput() LookupSourceAhaResultOutput {
	return o
}

func (o LookupSourceAhaResultOutput) ToLookupSourceAhaResultOutputWithContext(ctx context.Context) LookupSourceAhaResultOutput {
	return o
}

func (o LookupSourceAhaResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceAhaResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceAhaResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceAhaResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceAhaResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceAhaResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceAhaResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceAhaResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceAhaResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceAhaResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceAhaResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceAhaResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceAhaResultOutput{})
}
