// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSourceGoogleWebfonts(ctx *pulumi.Context, args *LookupSourceGoogleWebfontsArgs, opts ...pulumi.InvokeOption) (*LookupSourceGoogleWebfontsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceGoogleWebfontsResult
	err := ctx.Invoke("airbyte:index/getSourceGoogleWebfonts:getSourceGoogleWebfonts", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceGoogleWebfonts.
type LookupSourceGoogleWebfontsArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceGoogleWebfonts.
type LookupSourceGoogleWebfontsResult struct {
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceGoogleWebfontsOutput(ctx *pulumi.Context, args LookupSourceGoogleWebfontsOutputArgs, opts ...pulumi.InvokeOption) LookupSourceGoogleWebfontsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceGoogleWebfontsResult, error) {
			args := v.(LookupSourceGoogleWebfontsArgs)
			r, err := LookupSourceGoogleWebfonts(ctx, &args, opts...)
			var s LookupSourceGoogleWebfontsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceGoogleWebfontsResultOutput)
}

// A collection of arguments for invoking getSourceGoogleWebfonts.
type LookupSourceGoogleWebfontsOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceGoogleWebfontsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceGoogleWebfontsArgs)(nil)).Elem()
}

// A collection of values returned by getSourceGoogleWebfonts.
type LookupSourceGoogleWebfontsResultOutput struct{ *pulumi.OutputState }

func (LookupSourceGoogleWebfontsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceGoogleWebfontsResult)(nil)).Elem()
}

func (o LookupSourceGoogleWebfontsResultOutput) ToLookupSourceGoogleWebfontsResultOutput() LookupSourceGoogleWebfontsResultOutput {
	return o
}

func (o LookupSourceGoogleWebfontsResultOutput) ToLookupSourceGoogleWebfontsResultOutputWithContext(ctx context.Context) LookupSourceGoogleWebfontsResultOutput {
	return o
}

func (o LookupSourceGoogleWebfontsResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWebfontsResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceGoogleWebfontsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWebfontsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceGoogleWebfontsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWebfontsResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceGoogleWebfontsResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWebfontsResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceGoogleWebfontsResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWebfontsResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceGoogleWebfontsResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGoogleWebfontsResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceGoogleWebfontsResultOutput{})
}
