// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSourcePostgres(ctx *pulumi.Context, args *LookupSourcePostgresArgs, opts ...pulumi.InvokeOption) (*LookupSourcePostgresResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourcePostgresResult
	err := ctx.Invoke("airbyte:index/getSourcePostgres:getSourcePostgres", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourcePostgres.
type LookupSourcePostgresArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourcePostgres.
type LookupSourcePostgresResult struct {
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourcePostgresOutput(ctx *pulumi.Context, args LookupSourcePostgresOutputArgs, opts ...pulumi.InvokeOption) LookupSourcePostgresResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourcePostgresResult, error) {
			args := v.(LookupSourcePostgresArgs)
			r, err := LookupSourcePostgres(ctx, &args, opts...)
			var s LookupSourcePostgresResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourcePostgresResultOutput)
}

// A collection of arguments for invoking getSourcePostgres.
type LookupSourcePostgresOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourcePostgresOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourcePostgresArgs)(nil)).Elem()
}

// A collection of values returned by getSourcePostgres.
type LookupSourcePostgresResultOutput struct{ *pulumi.OutputState }

func (LookupSourcePostgresResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourcePostgresResult)(nil)).Elem()
}

func (o LookupSourcePostgresResultOutput) ToLookupSourcePostgresResultOutput() LookupSourcePostgresResultOutput {
	return o
}

func (o LookupSourcePostgresResultOutput) ToLookupSourcePostgresResultOutputWithContext(ctx context.Context) LookupSourcePostgresResultOutput {
	return o
}

func (o LookupSourcePostgresResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePostgresResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourcePostgresResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePostgresResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourcePostgresResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePostgresResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourcePostgresResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePostgresResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourcePostgresResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePostgresResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourcePostgresResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourcePostgresResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourcePostgresResultOutput{})
}
