// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSourceGainsightPx(ctx *pulumi.Context, args *LookupSourceGainsightPxArgs, opts ...pulumi.InvokeOption) (*LookupSourceGainsightPxResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceGainsightPxResult
	err := ctx.Invoke("airbyte:index/getSourceGainsightPx:getSourceGainsightPx", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceGainsightPx.
type LookupSourceGainsightPxArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceGainsightPx.
type LookupSourceGainsightPxResult struct {
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceGainsightPxOutput(ctx *pulumi.Context, args LookupSourceGainsightPxOutputArgs, opts ...pulumi.InvokeOption) LookupSourceGainsightPxResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceGainsightPxResult, error) {
			args := v.(LookupSourceGainsightPxArgs)
			r, err := LookupSourceGainsightPx(ctx, &args, opts...)
			var s LookupSourceGainsightPxResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceGainsightPxResultOutput)
}

// A collection of arguments for invoking getSourceGainsightPx.
type LookupSourceGainsightPxOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceGainsightPxOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceGainsightPxArgs)(nil)).Elem()
}

// A collection of values returned by getSourceGainsightPx.
type LookupSourceGainsightPxResultOutput struct{ *pulumi.OutputState }

func (LookupSourceGainsightPxResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceGainsightPxResult)(nil)).Elem()
}

func (o LookupSourceGainsightPxResultOutput) ToLookupSourceGainsightPxResultOutput() LookupSourceGainsightPxResultOutput {
	return o
}

func (o LookupSourceGainsightPxResultOutput) ToLookupSourceGainsightPxResultOutputWithContext(ctx context.Context) LookupSourceGainsightPxResultOutput {
	return o
}

func (o LookupSourceGainsightPxResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGainsightPxResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceGainsightPxResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGainsightPxResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceGainsightPxResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGainsightPxResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceGainsightPxResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGainsightPxResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceGainsightPxResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGainsightPxResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceGainsightPxResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceGainsightPxResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceGainsightPxResultOutput{})
}
