// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSourceIntercom(ctx *pulumi.Context, args *LookupSourceIntercomArgs, opts ...pulumi.InvokeOption) (*LookupSourceIntercomResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceIntercomResult
	err := ctx.Invoke("airbyte:index/getSourceIntercom:getSourceIntercom", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceIntercom.
type LookupSourceIntercomArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceIntercom.
type LookupSourceIntercomResult struct {
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceIntercomOutput(ctx *pulumi.Context, args LookupSourceIntercomOutputArgs, opts ...pulumi.InvokeOption) LookupSourceIntercomResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceIntercomResult, error) {
			args := v.(LookupSourceIntercomArgs)
			r, err := LookupSourceIntercom(ctx, &args, opts...)
			var s LookupSourceIntercomResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceIntercomResultOutput)
}

// A collection of arguments for invoking getSourceIntercom.
type LookupSourceIntercomOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceIntercomOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceIntercomArgs)(nil)).Elem()
}

// A collection of values returned by getSourceIntercom.
type LookupSourceIntercomResultOutput struct{ *pulumi.OutputState }

func (LookupSourceIntercomResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceIntercomResult)(nil)).Elem()
}

func (o LookupSourceIntercomResultOutput) ToLookupSourceIntercomResultOutput() LookupSourceIntercomResultOutput {
	return o
}

func (o LookupSourceIntercomResultOutput) ToLookupSourceIntercomResultOutputWithContext(ctx context.Context) LookupSourceIntercomResultOutput {
	return o
}

func (o LookupSourceIntercomResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceIntercomResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceIntercomResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceIntercomResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceIntercomResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceIntercomResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceIntercomResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceIntercomResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceIntercomResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceIntercomResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceIntercomResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceIntercomResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceIntercomResultOutput{})
}
