// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSourceTwilio(ctx *pulumi.Context, args *LookupSourceTwilioArgs, opts ...pulumi.InvokeOption) (*LookupSourceTwilioResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSourceTwilioResult
	err := ctx.Invoke("airbyte:index/getSourceTwilio:getSourceTwilio", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSourceTwilio.
type LookupSourceTwilioArgs struct {
	SourceId string `pulumi:"sourceId"`
}

// A collection of values returned by getSourceTwilio.
type LookupSourceTwilioResult struct {
	Configuration string `pulumi:"configuration"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
	SourceId    string `pulumi:"sourceId"`
	SourceType  string `pulumi:"sourceType"`
	WorkspaceId string `pulumi:"workspaceId"`
}

func LookupSourceTwilioOutput(ctx *pulumi.Context, args LookupSourceTwilioOutputArgs, opts ...pulumi.InvokeOption) LookupSourceTwilioResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSourceTwilioResult, error) {
			args := v.(LookupSourceTwilioArgs)
			r, err := LookupSourceTwilio(ctx, &args, opts...)
			var s LookupSourceTwilioResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSourceTwilioResultOutput)
}

// A collection of arguments for invoking getSourceTwilio.
type LookupSourceTwilioOutputArgs struct {
	SourceId pulumi.StringInput `pulumi:"sourceId"`
}

func (LookupSourceTwilioOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceTwilioArgs)(nil)).Elem()
}

// A collection of values returned by getSourceTwilio.
type LookupSourceTwilioResultOutput struct{ *pulumi.OutputState }

func (LookupSourceTwilioResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSourceTwilioResult)(nil)).Elem()
}

func (o LookupSourceTwilioResultOutput) ToLookupSourceTwilioResultOutput() LookupSourceTwilioResultOutput {
	return o
}

func (o LookupSourceTwilioResultOutput) ToLookupSourceTwilioResultOutputWithContext(ctx context.Context) LookupSourceTwilioResultOutput {
	return o
}

func (o LookupSourceTwilioResultOutput) Configuration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceTwilioResult) string { return v.Configuration }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSourceTwilioResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceTwilioResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSourceTwilioResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceTwilioResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupSourceTwilioResultOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceTwilioResult) string { return v.SourceId }).(pulumi.StringOutput)
}

func (o LookupSourceTwilioResultOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceTwilioResult) string { return v.SourceType }).(pulumi.StringOutput)
}

func (o LookupSourceTwilioResultOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSourceTwilioResult) string { return v.WorkspaceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSourceTwilioResultOutput{})
}
