// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package airbyte

import (
	"context"
	"reflect"

	"errors"
	"github.com/howly-global/pulumi-airbyte/sdk/go/airbyte/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SourceJira struct {
	pulumi.CustomResourceState

	Configuration SourceJiraConfigurationOutput `pulumi:"configuration"`
	// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided. Requires
	// replacement if changed.
	DefinitionId pulumi.StringPtrOutput `pulumi:"definitionId"`
	// Name of the source e.g. dev-mysql-instance.
	Name pulumi.StringOutput `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow. Requires replacement if changed.
	SecretId    pulumi.StringPtrOutput `pulumi:"secretId"`
	SourceId    pulumi.StringOutput    `pulumi:"sourceId"`
	SourceType  pulumi.StringOutput    `pulumi:"sourceType"`
	WorkspaceId pulumi.StringOutput    `pulumi:"workspaceId"`
}

// NewSourceJira registers a new resource with the given unique name, arguments, and options.
func NewSourceJira(ctx *pulumi.Context,
	name string, args *SourceJiraArgs, opts ...pulumi.ResourceOption) (*SourceJira, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Configuration == nil {
		return nil, errors.New("invalid value for required argument 'Configuration'")
	}
	if args.WorkspaceId == nil {
		return nil, errors.New("invalid value for required argument 'WorkspaceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SourceJira
	err := ctx.RegisterResource("airbyte:index/sourceJira:SourceJira", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSourceJira gets an existing SourceJira resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSourceJira(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SourceJiraState, opts ...pulumi.ResourceOption) (*SourceJira, error) {
	var resource SourceJira
	err := ctx.ReadResource("airbyte:index/sourceJira:SourceJira", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SourceJira resources.
type sourceJiraState struct {
	Configuration *SourceJiraConfiguration `pulumi:"configuration"`
	// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided. Requires
	// replacement if changed.
	DefinitionId *string `pulumi:"definitionId"`
	// Name of the source e.g. dev-mysql-instance.
	Name *string `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow. Requires replacement if changed.
	SecretId    *string `pulumi:"secretId"`
	SourceId    *string `pulumi:"sourceId"`
	SourceType  *string `pulumi:"sourceType"`
	WorkspaceId *string `pulumi:"workspaceId"`
}

type SourceJiraState struct {
	Configuration SourceJiraConfigurationPtrInput
	// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided. Requires
	// replacement if changed.
	DefinitionId pulumi.StringPtrInput
	// Name of the source e.g. dev-mysql-instance.
	Name pulumi.StringPtrInput
	// Optional secretID obtained through the public API OAuth redirect flow. Requires replacement if changed.
	SecretId    pulumi.StringPtrInput
	SourceId    pulumi.StringPtrInput
	SourceType  pulumi.StringPtrInput
	WorkspaceId pulumi.StringPtrInput
}

func (SourceJiraState) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceJiraState)(nil)).Elem()
}

type sourceJiraArgs struct {
	Configuration SourceJiraConfiguration `pulumi:"configuration"`
	// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided. Requires
	// replacement if changed.
	DefinitionId *string `pulumi:"definitionId"`
	// Name of the source e.g. dev-mysql-instance.
	Name *string `pulumi:"name"`
	// Optional secretID obtained through the public API OAuth redirect flow. Requires replacement if changed.
	SecretId    *string `pulumi:"secretId"`
	WorkspaceId string  `pulumi:"workspaceId"`
}

// The set of arguments for constructing a SourceJira resource.
type SourceJiraArgs struct {
	Configuration SourceJiraConfigurationInput
	// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided. Requires
	// replacement if changed.
	DefinitionId pulumi.StringPtrInput
	// Name of the source e.g. dev-mysql-instance.
	Name pulumi.StringPtrInput
	// Optional secretID obtained through the public API OAuth redirect flow. Requires replacement if changed.
	SecretId    pulumi.StringPtrInput
	WorkspaceId pulumi.StringInput
}

func (SourceJiraArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sourceJiraArgs)(nil)).Elem()
}

type SourceJiraInput interface {
	pulumi.Input

	ToSourceJiraOutput() SourceJiraOutput
	ToSourceJiraOutputWithContext(ctx context.Context) SourceJiraOutput
}

func (*SourceJira) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceJira)(nil)).Elem()
}

func (i *SourceJira) ToSourceJiraOutput() SourceJiraOutput {
	return i.ToSourceJiraOutputWithContext(context.Background())
}

func (i *SourceJira) ToSourceJiraOutputWithContext(ctx context.Context) SourceJiraOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceJiraOutput)
}

// SourceJiraArrayInput is an input type that accepts SourceJiraArray and SourceJiraArrayOutput values.
// You can construct a concrete instance of `SourceJiraArrayInput` via:
//
//	SourceJiraArray{ SourceJiraArgs{...} }
type SourceJiraArrayInput interface {
	pulumi.Input

	ToSourceJiraArrayOutput() SourceJiraArrayOutput
	ToSourceJiraArrayOutputWithContext(context.Context) SourceJiraArrayOutput
}

type SourceJiraArray []SourceJiraInput

func (SourceJiraArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SourceJira)(nil)).Elem()
}

func (i SourceJiraArray) ToSourceJiraArrayOutput() SourceJiraArrayOutput {
	return i.ToSourceJiraArrayOutputWithContext(context.Background())
}

func (i SourceJiraArray) ToSourceJiraArrayOutputWithContext(ctx context.Context) SourceJiraArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceJiraArrayOutput)
}

// SourceJiraMapInput is an input type that accepts SourceJiraMap and SourceJiraMapOutput values.
// You can construct a concrete instance of `SourceJiraMapInput` via:
//
//	SourceJiraMap{ "key": SourceJiraArgs{...} }
type SourceJiraMapInput interface {
	pulumi.Input

	ToSourceJiraMapOutput() SourceJiraMapOutput
	ToSourceJiraMapOutputWithContext(context.Context) SourceJiraMapOutput
}

type SourceJiraMap map[string]SourceJiraInput

func (SourceJiraMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SourceJira)(nil)).Elem()
}

func (i SourceJiraMap) ToSourceJiraMapOutput() SourceJiraMapOutput {
	return i.ToSourceJiraMapOutputWithContext(context.Background())
}

func (i SourceJiraMap) ToSourceJiraMapOutputWithContext(ctx context.Context) SourceJiraMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SourceJiraMapOutput)
}

type SourceJiraOutput struct{ *pulumi.OutputState }

func (SourceJiraOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SourceJira)(nil)).Elem()
}

func (o SourceJiraOutput) ToSourceJiraOutput() SourceJiraOutput {
	return o
}

func (o SourceJiraOutput) ToSourceJiraOutputWithContext(ctx context.Context) SourceJiraOutput {
	return o
}

func (o SourceJiraOutput) Configuration() SourceJiraConfigurationOutput {
	return o.ApplyT(func(v *SourceJira) SourceJiraConfigurationOutput { return v.Configuration }).(SourceJiraConfigurationOutput)
}

// The UUID of the connector definition. One of configuration.sourceType or definitionId must be provided. Requires
// replacement if changed.
func (o SourceJiraOutput) DefinitionId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SourceJira) pulumi.StringPtrOutput { return v.DefinitionId }).(pulumi.StringPtrOutput)
}

// Name of the source e.g. dev-mysql-instance.
func (o SourceJiraOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceJira) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optional secretID obtained through the public API OAuth redirect flow. Requires replacement if changed.
func (o SourceJiraOutput) SecretId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SourceJira) pulumi.StringPtrOutput { return v.SecretId }).(pulumi.StringPtrOutput)
}

func (o SourceJiraOutput) SourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceJira) pulumi.StringOutput { return v.SourceId }).(pulumi.StringOutput)
}

func (o SourceJiraOutput) SourceType() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceJira) pulumi.StringOutput { return v.SourceType }).(pulumi.StringOutput)
}

func (o SourceJiraOutput) WorkspaceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SourceJira) pulumi.StringOutput { return v.WorkspaceId }).(pulumi.StringOutput)
}

type SourceJiraArrayOutput struct{ *pulumi.OutputState }

func (SourceJiraArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SourceJira)(nil)).Elem()
}

func (o SourceJiraArrayOutput) ToSourceJiraArrayOutput() SourceJiraArrayOutput {
	return o
}

func (o SourceJiraArrayOutput) ToSourceJiraArrayOutputWithContext(ctx context.Context) SourceJiraArrayOutput {
	return o
}

func (o SourceJiraArrayOutput) Index(i pulumi.IntInput) SourceJiraOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SourceJira {
		return vs[0].([]*SourceJira)[vs[1].(int)]
	}).(SourceJiraOutput)
}

type SourceJiraMapOutput struct{ *pulumi.OutputState }

func (SourceJiraMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SourceJira)(nil)).Elem()
}

func (o SourceJiraMapOutput) ToSourceJiraMapOutput() SourceJiraMapOutput {
	return o
}

func (o SourceJiraMapOutput) ToSourceJiraMapOutputWithContext(ctx context.Context) SourceJiraMapOutput {
	return o
}

func (o SourceJiraMapOutput) MapIndex(k pulumi.StringInput) SourceJiraOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SourceJira {
		return vs[0].(map[string]*SourceJira)[vs[1].(string)]
	}).(SourceJiraOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SourceJiraInput)(nil)).Elem(), &SourceJira{})
	pulumi.RegisterInputType(reflect.TypeOf((*SourceJiraArrayInput)(nil)).Elem(), SourceJiraArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SourceJiraMapInput)(nil)).Elem(), SourceJiraMap{})
	pulumi.RegisterOutputType(SourceJiraOutput{})
	pulumi.RegisterOutputType(SourceJiraArrayOutput{})
	pulumi.RegisterOutputType(SourceJiraMapOutput{})
}
