// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationRedshiftConfigurationUploadingMethodAwss3StagingEncryptionNoEncryptionGetArgs : global::Pulumi.ResourceArgs
    {
        public DestinationRedshiftConfigurationUploadingMethodAwss3StagingEncryptionNoEncryptionGetArgs()
        {
        }
        public static new DestinationRedshiftConfigurationUploadingMethodAwss3StagingEncryptionNoEncryptionGetArgs Empty => new DestinationRedshiftConfigurationUploadingMethodAwss3StagingEncryptionNoEncryptionGetArgs();
    }
}
