// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationS3GlueConfigurationFormatJsonLinesNewlineDelimitedJsonCompressionGzipArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// must be one of ["GZIP"]; Default: "GZIP"
        /// </summary>
        [Input("compressionType")]
        public Input<string>? CompressionType { get; set; }

        public DestinationS3GlueConfigurationFormatJsonLinesNewlineDelimitedJsonCompressionGzipArgs()
        {
        }
        public static new DestinationS3GlueConfigurationFormatJsonLinesNewlineDelimitedJsonCompressionGzipArgs Empty => new DestinationS3GlueConfigurationFormatJsonLinesNewlineDelimitedJsonCompressionGzipArgs();
    }
}
