// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationAwsDatalakeConfigurationCredentialsArgs : global::Pulumi.ResourceArgs
    {
        [Input("iamRole")]
        public Input<Inputs.DestinationAwsDatalakeConfigurationCredentialsIamRoleArgs>? IamRole { get; set; }

        [Input("iamUser")]
        public Input<Inputs.DestinationAwsDatalakeConfigurationCredentialsIamUserArgs>? IamUser { get; set; }

        public DestinationAwsDatalakeConfigurationCredentialsArgs()
        {
        }
        public static new DestinationAwsDatalakeConfigurationCredentialsArgs Empty => new DestinationAwsDatalakeConfigurationCredentialsArgs();
    }
}
