// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationGcsConfigurationFormatAvroApacheAvroCompressionCodecZstandardArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// must be one of ["zstandard"]; Default: "zstandard"
        /// </summary>
        [Input("codec")]
        public Input<string>? Codec { get; set; }

        /// <summary>
        /// Negative levels are 'fast' modes akin to lz4 or snappy, levels above 9 are generally for archival purposes, and levels above 18 use a lot of memory. Default: 3
        /// </summary>
        [Input("compressionLevel")]
        public Input<int>? CompressionLevel { get; set; }

        /// <summary>
        /// If true, include a checksum with each data block. Default: false
        /// </summary>
        [Input("includeChecksum")]
        public Input<bool>? IncludeChecksum { get; set; }

        public DestinationGcsConfigurationFormatAvroApacheAvroCompressionCodecZstandardArgs()
        {
        }
        public static new DestinationGcsConfigurationFormatAvroApacheAvroCompressionCodecZstandardArgs Empty => new DestinationGcsConfigurationFormatAvroApacheAvroCompressionCodecZstandardArgs();
    }
}
