// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationQdrantConfigurationProcessingTextSplitterBySeparatorArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to keep the separator in the resulting chunks. Default: false
        /// </summary>
        [Input("keepSeparator")]
        public Input<bool>? KeepSeparator { get; set; }

        [Input("separators")]
        private InputList<string>? _separators;

        /// <summary>
        /// List of separator strings to split text fields by. The separator itself needs to be wrapped in double quotes, e.g. to split by the dot character, use ".". To split by a newline, use "\n".
        /// </summary>
        public InputList<string> Separators
        {
            get => _separators ?? (_separators = new InputList<string>());
            set => _separators = value;
        }

        public DestinationQdrantConfigurationProcessingTextSplitterBySeparatorArgs()
        {
        }
        public static new DestinationQdrantConfigurationProcessingTextSplitterBySeparatorArgs Empty => new DestinationQdrantConfigurationProcessingTextSplitterBySeparatorArgs();
    }
}
