// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationWeaviateConfigurationEmbeddingAzureOpenAiArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The base URL for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource
        /// </summary>
        [Input("apiBase", required: true)]
        public Input<string> ApiBase { get; set; } = null!;

        /// <summary>
        /// The deployment for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource
        /// </summary>
        [Input("deployment", required: true)]
        public Input<string> Deployment { get; set; } = null!;

        [Input("openaiKey", required: true)]
        private Input<string>? _openaiKey;

        /// <summary>
        /// The API key for your Azure OpenAI resource.  You can find this in the Azure portal under your Azure OpenAI resource
        /// </summary>
        public Input<string>? OpenaiKey
        {
            get => _openaiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _openaiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public DestinationWeaviateConfigurationEmbeddingAzureOpenAiArgs()
        {
        }
        public static new DestinationWeaviateConfigurationEmbeddingAzureOpenAiArgs Empty => new DestinationWeaviateConfigurationEmbeddingAzureOpenAiArgs();
    }
}
