// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationElasticsearchConfigurationAuthenticationMethodApiKeySecretGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Key ID to used when accessing an enterprise Elasticsearch instance.
        /// </summary>
        [Input("apiKeyId", required: true)]
        public Input<string> ApiKeyId { get; set; } = null!;

        /// <summary>
        /// The secret associated with the API Key ID.
        /// </summary>
        [Input("apiKeySecret", required: true)]
        public Input<string> ApiKeySecret { get; set; } = null!;

        public DestinationElasticsearchConfigurationAuthenticationMethodApiKeySecretGetArgs()
        {
        }
        public static new DestinationElasticsearchConfigurationAuthenticationMethodApiKeySecretGetArgs Empty => new DestinationElasticsearchConfigurationAuthenticationMethodApiKeySecretGetArgs();
    }
}
