// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationS3ConfigurationFormatArgs : global::Pulumi.ResourceArgs
    {
        [Input("avroApacheAvro")]
        public Input<Inputs.DestinationS3ConfigurationFormatAvroApacheAvroArgs>? AvroApacheAvro { get; set; }

        [Input("csvCommaSeparatedValues")]
        public Input<Inputs.DestinationS3ConfigurationFormatCsvCommaSeparatedValuesArgs>? CsvCommaSeparatedValues { get; set; }

        [Input("jsonLinesNewlineDelimitedJson")]
        public Input<Inputs.DestinationS3ConfigurationFormatJsonLinesNewlineDelimitedJsonArgs>? JsonLinesNewlineDelimitedJson { get; set; }

        [Input("parquetColumnarStorage")]
        public Input<Inputs.DestinationS3ConfigurationFormatParquetColumnarStorageArgs>? ParquetColumnarStorage { get; set; }

        public DestinationS3ConfigurationFormatArgs()
        {
        }
        public static new DestinationS3ConfigurationFormatArgs Empty => new DestinationS3ConfigurationFormatArgs();
    }
}
