// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationElasticsearchConfigurationAuthenticationMethodArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Use a api key and secret combination to authenticate
        /// </summary>
        [Input("apiKeySecret")]
        public Input<Inputs.DestinationElasticsearchConfigurationAuthenticationMethodApiKeySecretArgs>? ApiKeySecret { get; set; }

        /// <summary>
        /// Basic auth header with a username and password
        /// </summary>
        [Input("usernamePassword")]
        public Input<Inputs.DestinationElasticsearchConfigurationAuthenticationMethodUsernamePasswordArgs>? UsernamePassword { get; set; }

        public DestinationElasticsearchConfigurationAuthenticationMethodArgs()
        {
        }
        public static new DestinationElasticsearchConfigurationAuthenticationMethodArgs Empty => new DestinationElasticsearchConfigurationAuthenticationMethodArgs();
    }
}
