// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class DestinationMilvusConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Embedding configuration
        /// </summary>
        [Input("embedding", required: true)]
        public Input<Inputs.DestinationMilvusConfigurationEmbeddingGetArgs> Embedding { get; set; } = null!;

        /// <summary>
        /// Indexing configuration
        /// </summary>
        [Input("indexing", required: true)]
        public Input<Inputs.DestinationMilvusConfigurationIndexingGetArgs> Indexing { get; set; } = null!;

        /// <summary>
        /// Do not store the text that gets embedded along with the vector and the metadata in the destination. If set to true, only the vector and the metadata will be stored - in this case raw text for LLM use cases needs to be retrieved from another source. Default: false
        /// </summary>
        [Input("omitRawText")]
        public Input<bool>? OmitRawText { get; set; }

        [Input("processing", required: true)]
        public Input<Inputs.DestinationMilvusConfigurationProcessingGetArgs> Processing { get; set; } = null!;

        public DestinationMilvusConfigurationGetArgs()
        {
        }
        public static new DestinationMilvusConfigurationGetArgs Empty => new DestinationMilvusConfigurationGetArgs();
    }
}
