// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceYotpoConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessToken", required: true)]
        private Input<string>? _accessToken;

        /// <summary>
        /// Access token recieved as a result of API call to https://api.yotpo.com/oauth/token (Ref- https://apidocs.yotpo.com/reference/yotpo-authentication)
        /// </summary>
        public Input<string>? AccessToken
        {
            get => _accessToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("appKey", required: true)]
        private Input<string>? _appKey;

        /// <summary>
        /// App key found at settings (Ref- https://settings.yotpo.com/#/general_settings)
        /// </summary>
        public Input<string>? AppKey
        {
            get => _appKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _appKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Email address registered with yotpo. Default: "example@gmail.com"
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// Date time filter for incremental filter, Specify which date to extract from.
        /// </summary>
        [Input("startDate", required: true)]
        public Input<string> StartDate { get; set; } = null!;

        public SourceYotpoConfigurationArgs()
        {
        }
        public static new SourceYotpoConfigurationArgs Empty => new SourceYotpoConfigurationArgs();
    }
}
