// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceRetentlyConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Choose how to authenticate to Retently
        /// </summary>
        [Input("credentials")]
        public Input<Inputs.SourceRetentlyConfigurationCredentialsArgs>? Credentials { get; set; }

        public SourceRetentlyConfigurationArgs()
        {
        }
        public static new SourceRetentlyConfigurationArgs Empty => new SourceRetentlyConfigurationArgs();
    }
}
