// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceGoogleAnalyticsDataApiConfigurationCustomReportsArrayCohortSpecEnabledCohortsRangeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies the end date of the extended reporting date range for a cohort report.
        /// </summary>
        [Input("endOffset", required: true)]
        public Input<int> EndOffset { get; set; } = null!;

        /// <summary>
        /// The granularity used to interpret the startOffset and endOffset for the extended reporting date range for a cohort report. must be one of ["GRANULARITY_UNSPECIFIED", "DAILY", "WEEKLY", "MONTHLY"]
        /// </summary>
        [Input("granularity", required: true)]
        public Input<string> Granularity { get; set; } = null!;

        /// <summary>
        /// Specifies the start date of the extended reporting date range for a cohort report.
        /// </summary>
        [Input("startOffset")]
        public Input<int>? StartOffset { get; set; }

        public SourceGoogleAnalyticsDataApiConfigurationCustomReportsArrayCohortSpecEnabledCohortsRangeArgs()
        {
        }
        public static new SourceGoogleAnalyticsDataApiConfigurationCustomReportsArrayCohortSpecEnabledCohortsRangeArgs Empty => new SourceGoogleAnalyticsDataApiConfigurationCustomReportsArrayCohortSpecEnabledCohortsRangeArgs();
    }
}
