// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceAmazonSellerPartnerConfigurationReportOptionsListOptionsListGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("optionName", required: true)]
        public Input<string> OptionName { get; set; } = null!;

        [Input("optionValue", required: true)]
        public Input<string> OptionValue { get; set; } = null!;

        public SourceAmazonSellerPartnerConfigurationReportOptionsListOptionsListGetArgs()
        {
        }
        public static new SourceAmazonSellerPartnerConfigurationReportOptionsListOptionsListGetArgs Empty => new SourceAmazonSellerPartnerConfigurationReportOptionsListOptionsListGetArgs();
    }
}
