// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceMongodbV2ConfigurationDatabaseConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// MongoDB Atlas-hosted cluster configured as a replica set
        /// </summary>
        [Input("mongoDbAtlasReplicaSet")]
        public Input<Inputs.SourceMongodbV2ConfigurationDatabaseConfigMongoDbAtlasReplicaSetArgs>? MongoDbAtlasReplicaSet { get; set; }

        /// <summary>
        /// MongoDB self-hosted cluster configured as a replica set
        /// </summary>
        [Input("selfManagedReplicaSet")]
        public Input<Inputs.SourceMongodbV2ConfigurationDatabaseConfigSelfManagedReplicaSetArgs>? SelfManagedReplicaSet { get; set; }

        public SourceMongodbV2ConfigurationDatabaseConfigArgs()
        {
        }
        public static new SourceMongodbV2ConfigurationDatabaseConfigArgs Empty => new SourceMongodbV2ConfigurationDatabaseConfigArgs();
    }
}
