// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceTiktokMarketingConfigurationCredentialsOAuth20Args : global::Pulumi.ResourceArgs
    {
        [Input("accessToken", required: true)]
        private Input<string>? _accessToken;

        /// <summary>
        /// Long-term Authorized Access Token.
        /// </summary>
        public Input<string>? AccessToken
        {
            get => _accessToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The Advertiser ID to filter reports and streams. Let this empty to retrieve all.
        /// </summary>
        [Input("advertiserId")]
        public Input<string>? AdvertiserId { get; set; }

        /// <summary>
        /// The Developer Application App ID.
        /// </summary>
        [Input("appId", required: true)]
        public Input<string> AppId { get; set; } = null!;

        /// <summary>
        /// The Developer Application Secret.
        /// </summary>
        [Input("secret", required: true)]
        public Input<string> Secret { get; set; } = null!;

        public SourceTiktokMarketingConfigurationCredentialsOAuth20Args()
        {
        }
        public static new SourceTiktokMarketingConfigurationCredentialsOAuth20Args Empty => new SourceTiktokMarketingConfigurationCredentialsOAuth20Args();
    }
}
