// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceBingAdsConfigurationCustomReportArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the custom report, this name would be used as stream name
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// A list of available aggregations. Default: "[Hourly]"
        /// </summary>
        [Input("reportAggregation")]
        public Input<string>? ReportAggregation { get; set; }

        [Input("reportColumns", required: true)]
        private InputList<string>? _reportColumns;

        /// <summary>
        /// A list of available report object columns. You can find it in description of reporting object that you want to add to custom report.
        /// </summary>
        public InputList<string> ReportColumns
        {
            get => _reportColumns ?? (_reportColumns = new InputList<string>());
            set => _reportColumns = value;
        }

        /// <summary>
        /// The name of the the object derives from the ReportRequest object. You can find it in Bing Ads Api docs - Reporting API - Reporting Data Objects. must be one of ["AccountPerformanceReportRequest", "AdDynamicTextPerformanceReportRequest", "AdExtensionByAdReportRequest", "AdExtensionByKeywordReportRequest", "AdExtensionDetailReportRequest", "AdGroupPerformanceReportRequest", "AdPerformanceReportRequest", "AgeGenderAudienceReportRequest", "AudiencePerformanceReportRequest", "CallDetailReportRequest", "CampaignPerformanceReportRequest", "ConversionPerformanceReportRequest", "DestinationUrlPerformanceReportRequest", "DSAAutoTargetPerformanceReportRequest", "DSACategoryPerformanceReportRequest", "DSASearchQueryPerformanceReportRequest", "GeographicPerformanceReportRequest", "GoalsAndFunnelsReportRequest", "HotelDimensionPerformanceReportRequest", "HotelGroupPerformanceReportRequest", "KeywordPerformanceReportRequest", "NegativeKeywordConflictReportRequest", "ProductDimensionPerformanceReportRequest", "ProductMatchCountReportRequest", "ProductNegativeKeywordConflictReportRequest", "ProductPartitionPerformanceReportRequest", "ProductPartitionUnitPerformanceReportRequest", "ProductSearchQueryPerformanceReportRequest", "ProfessionalDemographicsAudienceReportRequest", "PublisherUsagePerformanceReportRequest", "SearchCampaignChangeHistoryReportRequest", "SearchQueryPerformanceReportRequest", "ShareOfVoiceReportRequest", "UserLocationPerformanceReportRequest"]
        /// </summary>
        [Input("reportingObject", required: true)]
        public Input<string> ReportingObject { get; set; } = null!;

        public SourceBingAdsConfigurationCustomReportArgs()
        {
        }
        public static new SourceBingAdsConfigurationCustomReportArgs Empty => new SourceBingAdsConfigurationCustomReportArgs();
    }
}
