// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceAsanaConfigurationCredentialsAuthenticateWithPersonalAccessTokenGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("personalAccessToken", required: true)]
        private Input<string>? _personalAccessToken;

        /// <summary>
        /// Asana Personal Access Token (generate yours &lt;a href="https://app.asana.com/0/developer-console"&gt;here&lt;/a&gt;).
        /// </summary>
        public Input<string>? PersonalAccessToken
        {
            get => _personalAccessToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _personalAccessToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public SourceAsanaConfigurationCredentialsAuthenticateWithPersonalAccessTokenGetArgs()
        {
        }
        public static new SourceAsanaConfigurationCredentialsAuthenticateWithPersonalAccessTokenGetArgs Empty => new SourceAsanaConfigurationCredentialsAuthenticateWithPersonalAccessTokenGetArgs();
    }
}
