// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceS3ConfigurationFormatJsonlGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The chunk size in bytes to process at a time in memory from each file. If your data is particularly wide and failing during schema detection, increasing this should solve it. Beware of raising this too high as you could hit OOM errors. Default: 0
        /// </summary>
        [Input("blockSize")]
        public Input<int>? BlockSize { get; set; }

        /// <summary>
        /// Whether newline characters are allowed in JSON values. Turning this on may affect performance. Leave blank to default to False. Default: false
        /// </summary>
        [Input("newlinesInValues")]
        public Input<bool>? NewlinesInValues { get; set; }

        /// <summary>
        /// How JSON fields outside of explicit_schema (if given) are treated. Check &lt;a href="https://arrow.apache.org/docs/python/generated/pyarrow.json.ParseOptions.html" target="_blank"&gt;PyArrow documentation&lt;/a&gt; for details. must be one of ["ignore", "infer", "error"]; Default: "infer"
        /// </summary>
        [Input("unexpectedFieldBehavior")]
        public Input<string>? UnexpectedFieldBehavior { get; set; }

        public SourceS3ConfigurationFormatJsonlGetArgs()
        {
        }
        public static new SourceS3ConfigurationFormatJsonlGetArgs Empty => new SourceS3ConfigurationFormatJsonlGetArgs();
    }
}
