// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceMicrosoftTeamsConfigurationCredentialsAuthenticateViaMicrosoftOAuth20GetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Client ID of your Microsoft Teams developer application.
        /// </summary>
        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        /// <summary>
        /// The Client Secret of your Microsoft Teams developer application.
        /// </summary>
        [Input("clientSecret", required: true)]
        public Input<string> ClientSecret { get; set; } = null!;

        [Input("refreshToken", required: true)]
        private Input<string>? _refreshToken;

        /// <summary>
        /// A Refresh Token to renew the expired Access Token.
        /// </summary>
        public Input<string>? RefreshToken
        {
            get => _refreshToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _refreshToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// A globally unique identifier (GUID) that is different than your organization name or domain. Follow these steps to obtain: open one of the Teams where you belong inside the Teams Application &gt; Click on the … next to the Team title &gt; Click on Get link to team &gt; Copy the link to the team and grab the tenant ID form the URL
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public SourceMicrosoftTeamsConfigurationCredentialsAuthenticateViaMicrosoftOAuth20GetArgs()
        {
        }
        public static new SourceMicrosoftTeamsConfigurationCredentialsAuthenticateViaMicrosoftOAuth20GetArgs Empty => new SourceMicrosoftTeamsConfigurationCredentialsAuthenticateViaMicrosoftOAuth20GetArgs();
    }
}
