// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceOracleConfigurationTunnelMethodGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("noTunnel")]
        public Input<Inputs.SourceOracleConfigurationTunnelMethodNoTunnelGetArgs>? NoTunnel { get; set; }

        [Input("passwordAuthentication")]
        public Input<Inputs.SourceOracleConfigurationTunnelMethodPasswordAuthenticationGetArgs>? PasswordAuthentication { get; set; }

        [Input("sshKeyAuthentication")]
        public Input<Inputs.SourceOracleConfigurationTunnelMethodSshKeyAuthenticationGetArgs>? SshKeyAuthentication { get; set; }

        public SourceOracleConfigurationTunnelMethodGetArgs()
        {
        }
        public static new SourceOracleConfigurationTunnelMethodGetArgs Empty => new SourceOracleConfigurationTunnelMethodGetArgs();
    }
}
