// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceFakerConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Should the updated_at values for every record be new each sync?  Setting this to false will case the source to stop emitting records after COUNT records have been emitted. Default: true
        /// </summary>
        [Input("alwaysUpdated")]
        public Input<bool>? AlwaysUpdated { get; set; }

        /// <summary>
        /// How many users should be generated in total. The purchases table will be scaled to match, with 10 purchases created per 10 users. This setting does not apply to the products stream. Default: 1000
        /// </summary>
        [Input("count")]
        public Input<int>? Count { get; set; }

        /// <summary>
        /// How many parallel workers should we use to generate fake data?  Choose a value equal to the number of CPUs you will allocate to this source. Default: 4
        /// </summary>
        [Input("parallelism")]
        public Input<int>? Parallelism { get; set; }

        /// <summary>
        /// How many fake records will be in each page (stream slice), before a state message is emitted?. Default: 1000
        /// </summary>
        [Input("recordsPerSlice")]
        public Input<int>? RecordsPerSlice { get; set; }

        /// <summary>
        /// Manually control the faker random seed to return the same values on subsequent runs (leave -1 for random). Default: -1
        /// </summary>
        [Input("seed")]
        public Input<int>? Seed { get; set; }

        public SourceFakerConfigurationArgs()
        {
        }
        public static new SourceFakerConfigurationArgs Empty => new SourceFakerConfigurationArgs();
    }
}
