// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceOracleConfigurationEncryptionNativeNetworkEncryptionNneArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// This parameter defines what encryption algorithm is used. must be one of ["AES256", "RC4_56", "3DES168"]; Default: "AES256"
        /// </summary>
        [Input("encryptionAlgorithm")]
        public Input<string>? EncryptionAlgorithm { get; set; }

        public SourceOracleConfigurationEncryptionNativeNetworkEncryptionNneArgs()
        {
        }
        public static new SourceOracleConfigurationEncryptionNativeNetworkEncryptionNneArgs Empty => new SourceOracleConfigurationEncryptionNativeNetworkEncryptionNneArgs();
    }
}
