// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceShopifyConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defines what would be a date range per single BULK Job. Default: 30
        /// </summary>
        [Input("bulkWindowInDays")]
        public Input<int>? BulkWindowInDays { get; set; }

        /// <summary>
        /// The authorization method to use to retrieve data from Shopify
        /// </summary>
        [Input("credentials")]
        public Input<Inputs.SourceShopifyConfigurationCredentialsGetArgs>? Credentials { get; set; }

        /// <summary>
        /// Defines which API type (REST/BULK) to use to fetch `Transactions` data. If you are a `Shopify Plus` user, leave the default value to speed up the fetch. Default: false
        /// </summary>
        [Input("fetchTransactionsUserId")]
        public Input<bool>? FetchTransactionsUserId { get; set; }

        /// <summary>
        /// The name of your Shopify store found in the URL. For example, if your URL was https://NAME.myshopify.com, then the name would be 'NAME' or 'NAME.myshopify.com'.
        /// </summary>
        [Input("shop", required: true)]
        public Input<string> Shop { get; set; } = null!;

        /// <summary>
        /// The date you would like to replicate data from. Format: YYYY-MM-DD. Any data before this date will not be replicated. Default: "2020-01-01"
        /// </summary>
        [Input("startDate")]
        public Input<string>? StartDate { get; set; }

        public SourceShopifyConfigurationGetArgs()
        {
        }
        public static new SourceShopifyConfigurationGetArgs Empty => new SourceShopifyConfigurationGetArgs();
    }
}
