// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceWoocommerceConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiKey", required: true)]
        private Input<string>? _apiKey;

        /// <summary>
        /// Customer Key for API in WooCommerce shop
        /// </summary>
        public Input<string>? ApiKey
        {
            get => _apiKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apiKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Customer Secret for API in WooCommerce shop
        /// </summary>
        [Input("apiSecret", required: true)]
        public Input<string> ApiSecret { get; set; } = null!;

        /// <summary>
        /// The name of the store. For https://EXAMPLE.com, the shop name is 'EXAMPLE.com'.
        /// </summary>
        [Input("shop", required: true)]
        public Input<string> Shop { get; set; } = null!;

        /// <summary>
        /// The date you would like to replicate data from. Format: YYYY-MM-DD
        /// </summary>
        [Input("startDate", required: true)]
        public Input<string> StartDate { get; set; } = null!;

        public SourceWoocommerceConfigurationGetArgs()
        {
        }
        public static new SourceWoocommerceConfigurationGetArgs Empty => new SourceWoocommerceConfigurationGetArgs();
    }
}
