// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceOutbrainAmplifyConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Credentials for making authenticated requests requires either username/password or access_token.
        /// </summary>
        [Input("credentials", required: true)]
        public Input<Inputs.SourceOutbrainAmplifyConfigurationCredentialsGetArgs> Credentials { get; set; } = null!;

        /// <summary>
        /// Date in the format YYYY-MM-DD.
        /// </summary>
        [Input("endDate")]
        public Input<string>? EndDate { get; set; }

        /// <summary>
        /// The granularity used for geo location data in reports. must be one of ["country", "region", "subregion"]
        /// </summary>
        [Input("geoLocationBreakdown")]
        public Input<string>? GeoLocationBreakdown { get; set; }

        /// <summary>
        /// The granularity used for periodic data in reports. See &lt;a href="https://amplifyv01.docs.apiary.io/#reference/performance-reporting/periodic/retrieve-performance-statistics-for-all-marketer-campaigns-by-periodic-breakdown"&gt;the docs&lt;/a&gt;. must be one of ["daily", "weekly", "monthly"]
        /// </summary>
        [Input("reportGranularity")]
        public Input<string>? ReportGranularity { get; set; }

        /// <summary>
        /// Date in the format YYYY-MM-DD eg. 2017-01-25. Any data before this date will not be replicated.
        /// </summary>
        [Input("startDate", required: true)]
        public Input<string> StartDate { get; set; } = null!;

        public SourceOutbrainAmplifyConfigurationGetArgs()
        {
        }
        public static new SourceOutbrainAmplifyConfigurationGetArgs Empty => new SourceOutbrainAmplifyConfigurationGetArgs();
    }
}
