// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceNotionConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Choose either OAuth (recommended for Airbyte Cloud) or Access Token. See our &lt;a href='https://docs.airbyte.com/integrations/sources/notion#setup-guide'&gt;docs&lt;/a&gt; for more information.
        /// </summary>
        [Input("credentials")]
        public Input<Inputs.SourceNotionConfigurationCredentialsGetArgs>? Credentials { get; set; }

        /// <summary>
        /// UTC date and time in the format YYYY-MM-DDTHH:MM:SS.000Z. During incremental sync, any data generated before this date will not be replicated. If left blank, the start date will be set to 2 years before the present date.
        /// </summary>
        [Input("startDate")]
        public Input<string>? StartDate { get; set; }

        public SourceNotionConfigurationGetArgs()
        {
        }
        public static new SourceNotionConfigurationGetArgs Empty => new SourceNotionConfigurationGetArgs();
    }
}
