// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourcePostgresConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the database.
        /// </summary>
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        /// <summary>
        /// Hostname of the database.
        /// </summary>
        [Input("host", required: true)]
        public Input<string> Host { get; set; } = null!;

        /// <summary>
        /// Additional properties to pass to the JDBC URL string when connecting to the database formatted as 'key=value' pairs separated by the symbol '&amp;'. (Eg. key1=value1&amp;key2=value2&amp;key3=value3). For more information read about &lt;a href="https://jdbc.postgresql.org/documentation/head/connect.html"&gt;JDBC URL parameters&lt;/a&gt;.
        /// </summary>
        [Input("jdbcUrlParams")]
        public Input<string>? JdbcUrlParams { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Password associated with the username.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Port of the database. Default: 5432
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// Configures how data is extracted from the database.
        /// </summary>
        [Input("replicationMethod")]
        public Input<Inputs.SourcePostgresConfigurationReplicationMethodGetArgs>? ReplicationMethod { get; set; }

        [Input("schemas")]
        private InputList<string>? _schemas;

        /// <summary>
        /// The list of schemas (case sensitive) to sync from. Defaults to public.
        /// </summary>
        public InputList<string> Schemas
        {
            get => _schemas ?? (_schemas = new InputList<string>());
            set => _schemas = value;
        }

        /// <summary>
        /// SSL connection modes. 
        ///   Read more &lt;a href="https://jdbc.postgresql.org/documentation/head/ssl-client.html"&gt; in the docs&lt;/a&gt;.
        /// </summary>
        [Input("sslMode")]
        public Input<Inputs.SourcePostgresConfigurationSslModeGetArgs>? SslMode { get; set; }

        /// <summary>
        /// Whether to initiate an SSH tunnel before connecting to the database, and if so, which kind of authentication to use.
        /// </summary>
        [Input("tunnelMethod")]
        public Input<Inputs.SourcePostgresConfigurationTunnelMethodGetArgs>? TunnelMethod { get; set; }

        /// <summary>
        /// Username to access the database.
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public SourcePostgresConfigurationGetArgs()
        {
        }
        public static new SourcePostgresConfigurationGetArgs Empty => new SourcePostgresConfigurationGetArgs();
    }
}
