// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceGoogleDirectoryConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Google APIs use the OAuth 2.0 protocol for authentication and authorization. The Source supports &lt;a href="https://developers.google.com/identity/protocols/oauth2#webserver" target="_blank"&gt;Web server application&lt;/a&gt; and &lt;a href="https://developers.google.com/identity/protocols/oauth2#serviceaccount" target="_blank"&gt;Service accounts&lt;/a&gt; scenarios.
        /// </summary>
        [Input("credentials")]
        public Input<Inputs.SourceGoogleDirectoryConfigurationCredentialsArgs>? Credentials { get; set; }

        public SourceGoogleDirectoryConfigurationArgs()
        {
        }
        public static new SourceGoogleDirectoryConfigurationArgs Empty => new SourceGoogleDirectoryConfigurationArgs();
    }
}
