// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceS3ConfigurationFormatAvroArgs : global::Pulumi.ResourceArgs
    {
        public SourceS3ConfigurationFormatAvroArgs()
        {
        }
        public static new SourceS3ConfigurationFormatAvroArgs Empty => new SourceS3ConfigurationFormatAvroArgs();
    }
}
