// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceLinkedinPagesConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("credentials")]
        public Input<Inputs.SourceLinkedinPagesConfigurationCredentialsGetArgs>? Credentials { get; set; }

        /// <summary>
        /// Specify the Organization ID
        /// </summary>
        [Input("orgId", required: true)]
        public Input<string> OrgId { get; set; } = null!;

        public SourceLinkedinPagesConfigurationGetArgs()
        {
        }
        public static new SourceLinkedinPagesConfigurationGetArgs Empty => new SourceLinkedinPagesConfigurationGetArgs();
    }
}
