// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceFileConfigurationProviderS3AmazonWebServicesGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("awsAccessKeyId")]
        private Input<string>? _awsAccessKeyId;

        /// <summary>
        /// In order to access private Buckets stored on AWS S3, this connector would need credentials with the proper permissions. If accessing publicly available data, this field is not necessary.
        /// </summary>
        public Input<string>? AwsAccessKeyId
        {
            get => _awsAccessKeyId;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _awsAccessKeyId = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("awsSecretAccessKey")]
        private Input<string>? _awsSecretAccessKey;

        /// <summary>
        /// In order to access private Buckets stored on AWS S3, this connector would need credentials with the proper permissions. If accessing publicly available data, this field is not necessary.
        /// </summary>
        public Input<string>? AwsSecretAccessKey
        {
            get => _awsSecretAccessKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _awsSecretAccessKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public SourceFileConfigurationProviderS3AmazonWebServicesGetArgs()
        {
        }
        public static new SourceFileConfigurationProviderS3AmazonWebServicesGetArgs Empty => new SourceFileConfigurationProviderS3AmazonWebServicesGetArgs();
    }
}
