// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Airbyte.Inputs
{

    public sealed class SourceLeverHiringConfigurationCredentialsAuthenticateViaLeverOAuthArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Client ID of your Lever Hiring developer application.
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        /// <summary>
        /// The Client Secret of your Lever Hiring developer application.
        /// </summary>
        [Input("clientSecret")]
        public Input<string>? ClientSecret { get; set; }

        [Input("refreshToken", required: true)]
        private Input<string>? _refreshToken;

        /// <summary>
        /// The token for obtaining new access token.
        /// </summary>
        public Input<string>? RefreshToken
        {
            get => _refreshToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _refreshToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public SourceLeverHiringConfigurationCredentialsAuthenticateViaLeverOAuthArgs()
        {
        }
        public static new SourceLeverHiringConfigurationCredentialsAuthenticateViaLeverOAuthArgs Empty => new SourceLeverHiringConfigurationCredentialsAuthenticateViaLeverOAuthArgs();
    }
}
